### ISSUE TITLE
Create connection details in Airflow Connections

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/libsys-airflow#1023]
- [x] POD
- [x] SHAREVDE
- [x] GOBI
- OCLC:
- -[x] Lane
- -[x] Hoover
- -[x] GSB
- -[x] Law
- -[x] SUL

**Comment by shelleydoljack** [comment]
connection_id sharevde created on dev/stage/prod.

**Comment by shelleydoljack** [comment]
connection_id gobi created on dev/stage/prod.

**Comment by shelleydoljack** [comment]
@jermnelson Maybe we can pair on this for OCLC? I see the data in vault at `puppet/application/libsys_airflow/oclc` but I'm not entirely sure how the connection data was modeled as you tested it locally. There isn't a test for transmit_data_oclc_api_task that mocks the connection details and I can't quite tell how [the task called from the dag](https://github.com/sul-dlss/libsys-airflow/blob/7b669ec816a50f957a5218e2b50cba6472a592f2/libsys_airflow/dags/data_exports/oclc_transmission.py#L43-L52) and the [connection details are parsed](https://github.com/sul-dlss/libsys-airflow/blob/7b669ec816a50f957a5218e2b50cba6472a592f2/libsys_airflow/plugins/data_exports/transmission_tasks.py#L165-L171) out for each library.

This is what I did on dev but it doesn't seem right:
https://sul-libsys-airflow-dev.stanford.edu/connection/edit/70

**Comment by jermnelson** [comment]
Hi @shelleydoljack, happy to pair on this; looking at the `http-web.oclc-SUL` connection you created seems correct.  I haven't tested this beyond instantiating an instance of the OCLC API class based on the connection's credentials.

**Comment by shelleydoljack** [comment]
Ahh, ok. I'll keep going with what I created and add a test. :)

**Comment by shelleydoljack** [comment]
OCLC connections for GSB, MED, LANE, LAW, SUL created in airflow dev/stage/prod.
