### ISSUE TITLE
GOBI selection DAG failing on transform

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#1026]
https://sul-libsys-airflow-dev.stanford.edu/dags/select_gobi_records/grid?run_id=manual__2024-05-24T17%3A59%3A43%2B00%3A00&execution_date=2024-05-24+17%3A59%3A43%2B00%3A00&tab=logs&dag_run_id=manual__2024-05-24T17%3A59%3A43%2B00%3A00&task_id=transform_folio_marc_record

**Comment by jgreben** [comment]
See #1030

**Comment by ahafele** [comment]
@jgreben I tried to retest - the DAG is successful but no new files are generated. Do the old ones need to be removed first?

**Comment by jgreben** [comment]
Yes, I did not activate the gobi transmission dag so it was just appending to the previous generated file. I activated it so now hopefully it will work as intended.

**Comment by ahafele** [comment]
Same result. @jgreben could you delete all the gobi files and I'll try with a fresh start?

**Comment by ahafele** [comment]
Working now.
