### ISSUE TITLE
POD Data QA cont. 

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#1049]
1. New file is getting only holdings info in the 999 and it is duplicated. Update file looks good. 

2. Something changed from last week and the leader byte 05 in the new and update files is now getting changed to d. This should only be the case for the delete file. 

<img width="733" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFF3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--01bfe1242cb77a43c9eeb8a1a5e4cf0e01bf0e37/Screenshot%202024-06-03%20at%209.58.33%E2%80%AFAM.png" alt="Screenshot 2024-06-03 at 9.58.33 AM.png" />

**Comment by jgreben** [comment]
Looks like the deletes list also now contains the new and updates files:
`
{'new': ['/opt/airflow/data-export-files/pod/marc-files/new/202406031650.mrc'], 'updates': ['/opt/airflow/data-export-files/pod/marc-files/new/202406031650.mrc', '/opt/airflow/data-export-files/pod/marc-files/updates/202406031650.mrc'], 'deletes': ['/opt/airflow/data-export-files/pod/marc-files/new/202406031650.mrc', '/opt/airflow/data-export-files/pod/marc-files/updates/202406031650.mrc', '/opt/airflow/data-export-files/pod/marc-files/deletes/202406031650.mrc']}
`

And for that matter, the updates list also includes the new. Everything is getting cascade-added to the the subsequent lists.

**Comment by jgreben** [comment]
I suspect both issues 1 and 2 have to do with this bug.

**Comment by jgreben** [comment]
I added this to the `test_marc_for_instances` test and now the test fails:

```
assert not any("updates" in s for s in files["deletes"])
```

Will now work on fixing the function.
