### ISSUE TITLE
OCLC Export QA - Set holdings (updates)

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#1069]
Setting holdings in OCLC worked for first simple test! But the subsequent editing of the MARC record is not happening yet and I'm not sure if it is a bug or a missed requirement. 

When holdings are set in OCLC, e.g. Record has one unique OCLC record id, then do the following - 

> If the response code is 200, change the OCLC record id prefix in the instance record from (OCoLC) to (OCoLC-M) if it is not already that.
> If the response code is something other than 200, then appropriate action should be taken to resolve the problem, either by Systems or by Data Control, depending on the nature of the problem.

**Comment by jermnelson** [comment]
@ahafele I think this is a missed requirement.

**Comment by ahafele** [comment]
Will ticket failure part separately 

> If the response code is something other than 200, then appropriate action should be taken to resolve the problem, either by Systems or by Data Control, depending on the nature of the problem.

**Comment by shelleydoljack** [comment]
@ahafele I'm a little concerned about this new requirement and want to understand it more. Are we saying that the number we get back from OCLC is the master record number and therefore should have the `-M` added to the prefix when we add it to our MARC in SRS? Do we know that when there is one match in OCLC it means it is the master record number?

**Comment by ahafele** [comment]
@shelleydoljack to be clear this isn't a new requirement, but a missed one. As I understand it, the -M indicates to our staff that our holdings have been set. You can see comments from Vitus here https://docs.google.com/document/d/1TSU4DmWXKiL8UEjwighcMijeL6xl_6kXSO1QzDyRDVM/edit?disco=AAAA8tPB6dA
For these records, we are not adding an OCLC number to our record only updating the prefix. (though that does make me wonder about the new record stream).

**Comment by shelleydoljack** [comment]
🤔 I guess I'm just wondering what the `-M` means outside of it being used by staff to indicate that our holdings have been set. I tried searching for an answer and couldn't find anything definitive and honestly, I'm afraid of the answer if I ask the Metadata folks. Maybe I'm confusing this with prefixes and the conversation in SearchWorks meetings about them either being in our records or not being in our records. Some things I found: https://help.oclc.org/Metadata_Services/WorldShare_Collection_Manager/Data_sync_collections/Prepare_your_data/30035_field_and_OCLC_control_numbers
https://consul.stanford.edu/display/ACQMR/001%2C+035%2C+079+Fields
https://consul.stanford.edu/pages/viewpage.action?pageId=159745768

Ahh yes, okay, what Vitus outlined in the google doc seems right, based on how we used to process these fields. Note, we don't create institutional records anymore so the acq documention is a bit outdated. Thanks for this; I needed to refresh my memory on these things. 

Yea, we should evaluate what needs to happen for new records. It looks like that is "group 3" from his google doc?

**Comment by ahafele** [comment]
Correct, Group 3. I confirmed with Jeanette that when we insert OCLC numbers back into **new** records, they should also have the -M. cc @jermnelson I believe this answers your question [here](https://github.com/sul-dlss/libsys-airflow/pull/1075#discussion_r1639066892)
