### ISSUE TITLE
OCLC Exports QA - New upload not working

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#1070]
I tested uploaded a csv for "new" and the DAG is successful but it looks like no file is created 

https://sul-libsys-airflow-dev.stanford.edu/dags/select_oclc_records/grid?run_id=manual__2024-06-11T12%3A55%3A26.723711%2B00%3A00&execution_date=2024-06-11+12%3A55%3A26.723711%2B00%3A00&tab=graph&dag_run_id=manual__2024-06-11T12%3A55%3A26.723711%2B00%3A00 

Record used - https://folio-test.stanford.edu/inventory/view/64c8edc4-9dcf-40ee-8146-ed002eb933ba

**Comment by jermnelson** [comment]
Closing, record https://folio-test.stanford.edu/inventory/view/64c8edc4-9dcf-40ee-8146-ed002eb933ba was missing a Holdings record so we couldn't determine  the coordinate library and so no MARC records were written to file system.
