### ISSUE TITLE
OCLC Export QA - download files for other campuses 

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#1072]
I ran test for Lane and the update in OCLC was successful but I don't see the file available for download in the UI. The xcom references the filename /opt/airflow/data-export-files/oclc/marc-files/updates/202406121522-CASUM.mrc so maybe it is just a matter of surfacing?

https://sul-libsys-airflow-dev.stanford.edu/dags/send_oclc_records/grid?run_id=manual__2024-06-12T15%3A26%3A26.101060%2B00%3A00&execution_date=2024-06-12+15%3A26%3A26.101060%2B00%3A00&tab=xcom&dag_run_id=manual__2024-06-12T15%3A26%3A26.101060%2B00%3A00&task_id=transmit_data_oclc_api_task

**Comment by ahafele** [comment]
Hmm, this might be more than I thought. 
I just tried a test for new records and again the Lane file is not available but I don't see it referenced anywhere, so not sure why it wasn't created? The xcom for this dag run doesn't show any filenames. 

https://sul-libsys-airflow-dev.stanford.edu/dags/send_oclc_records/grid?run_id=manual__2024-06-12T18%3A17%3A18.555497%2B00%3A00&execution_date=2024-06-12+18%3A17%3A18.555497%2B00%3A00&tab=xcom&dag_run_id=manual__2024-06-12T18%3A17%3A18.555497%2B00%3A00&task_id=transmit_data_oclc_api_task

**Comment by jermnelson** [comment]
Hi @ahafele, I found `202406121522-CASUM.mrc` when searching the UI for that specific file.
![Screenshot 2024-06-13 at 10 51 21 AM](https://github.com/sul-dlss/libsys-airflow/assets/71847/87e6218b-fd85-4e01-801c-6bc111e9ab31)

I also found it when browsing to the second page when searching for oclc:
![Screenshot 2024-06-13 at 11 35 40 AM](https://github.com/sul-dlss/libsys-airflow/assets/71847/2c5419c2-ca2c-48c0-9ae6-ff75c854edaf)

Could you run a second test with the new records for Lane now that change in PR #1074 were deployed to dev?

Thanks!

**Comment by ahafele** [comment]
Yup, looks like a bunch new files are there after that PR was deployed. I'll keep testing.
