### ISSUE TITLE
POD (and GOBI) DAGs not producing files that are accessible via UI

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#1073]
The select and send DAGs are running successfully but no files are made available via the UI. Last file I see is dated 6/11. Testing on hold till resolved. 

Select dag run - https://sul-libsys-airflow-dev.stanford.edu/dags/select_pod_records/graph?run_id=manual__2024-06-13T13:30:40%2B00:00&execution_date=2024-06-13+13:30:40%2B00:00

Send dag run - https://sul-libsys-airflow-dev.stanford.edu/dags/send_pod_records/graph?run_id=manual__2024-06-13T13:35:15.481468%2B00:00&execution_date=2024-06-13+13:35:15.481468%2B00:00

**Comment by shelleydoljack** [comment]
The xcom for fetch_record_ids_from_folio contains the return_value with the list of new instance id's, but the save_ids_to_file returns an empty list (it should return a list of csv filenames I believe, as in [previous run from 6/4/2024](https://sul-libsys-airflow-dev.stanford.edu/dags/select_pod_records/grid?run_id=manual__2024-06-04T13%3A30%3A40%2B00%3A00&execution_date=2024-06-13+13%3A30%3A40%2B00%3A00&tab=xcom&dag_run_id=manual__2024-06-04T13%3A40%3A52.849868%2B00%3A00&base_date=2024-06-04T13%3A30%3A40Z&task_id=save_ids_to_file)).
