### ISSUE TITLE
OCLC - reporting

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#1080]
In addition to the 2 general email reports in #1079 and #861, OCLC requires a number of specialized reports for staff processing. These reports should be split by campus code and sent to specific email addresses (see below and referenced here #1035) _and_ sul-unicorn-devs@lists.stanford.edu.
**During testing please just send to sul-unicorn-devs**

1. Record has more than one OCLC record id (and therefore not new, update (set holdings), or delete (unset holdings))

Subject/body:

"OCLC: multiple OCLC IDs"

- Date of DAG run
- Report (or link to report) with list of record HRIDs or UUIDs

2. Matches - if the response code is something other than 200 and not resolvable by airflow task.

Subject/body:

"OCLC: Match error"

- Date of DAG run
- Report (or link to report) with list of record HRIDs or UUIDs and 
- OCLC response and response message

3. Updates (Set holdings) - if the response code is something other than 200 and not resolvable by airflow task.
**NOTE: we are currently setting holdings in two tasks - match and set holdings - so will need to account for both in this report. 

Subject/body:

"OCLC: Set holdings error"

- Date of DAG run
- Report (or link to report) with list of record HRIDs or UUIDs and 
- OCLC response and response message

3b. Deletes (Unset holdings) - if the response code is something other than 200 or if the response code is 200 but any message other than "Unset Holdings Succeeded." or "WorldCat Holding already unset."

Subject/body:

"OCLC: Unset holdings error"

- Date of DAG run
- Report (or link to report) with list of record HRIDs or UUIDs and 
- OCLC response and response message

Example response 

[2024-07-26, 09:59:56 PDT] {oclc_api.py:281} INFO - Delete 1107750624, holdings_unset call response <Response [200]> body: b'{\n  "controlNumber" : "1107750624",\n  "requestedControlNumber" : "1107750624",\n  "institutionCode" : "6617",\n  "institutionSymbol" : "STF",\n  "firstTimeUse" : false,\n  "success" : false,\n  "message" : "Unset Holdings Failed. Local bibliographic data (LBD) is attached to this record. To unset the holding, delete attached LBD first and try again.",\n  "action" : "Unset Holdings"\n}'

[2024-07-26, 10:27:46 PDT] {oclc_api.py:281} INFO - Delete 1320819277, holdings_unset call response <Response [200]> body: b'{\n  "controlNumber" : "1320819277",\n  "requestedControlNumber" : "1320819277",\n  "institutionCode" : "6617",\n  "institutionSymbol" : "STF",\n  "firstTimeUse" : false,\n  "success" : true,\n  "message" : "Unset Holdings Succeeded.",\n  "action" : "Unset Holdings"\n}'

4. New - if the response code is something other than 200 and not resolvable by airflow task.

Subject/body:

"OCLC: New record error(s)"

- Date of DAG run
- Report (or link to report) with list of record HRIDs or UUIDs and 
- OCLC response and response message

4b. New - Record validation errors. Send user all errorlevels and instance UUID. 

Subject/body:

"OCLC: New record validation errors"

- Date of DAG run
- Report (or link to report) with list of record HRIDs or UUIDs and error(s) from OCLC

Example OCLC response
[2024-07-26, 10:28:03 PDT] {oclc_api.py:247} ERROR - Instance UUID d50e776b-a2ed-4740-a94d-9d858db98ccb Error: 400 Client Error:  for url: https://metadata.api.oclc.org/worldcat/manage/bibs. Server response: {
  "errorCount" : 5,
  "errors" : [ "Invalid relationship - when Encoding Level (Leader/17) is equal to 1, then $b in 040 must be present.", "Invalid character h in position 2 in 1st $c in 040.", "Invalid character t in position 3 in 1st $d in 040.", "Invalid symbol NhCcYBP in 1st $c in 040.", "Invalid symbol CSt in 1st $d in 040." ],
  "fixedFieldErrors" : [ {
    "tag" : "000",
    "errorLevel" : "MINOR",
    "message" : "Invalid relationship - when Encoding Level (Leader/17) is equal to 1, then $b in 040 must be present."
  } ],
  "variableFieldErrors" : [ {
    "tag" : "040",
    "errorLevel" : "CRITICAL",
    "message" : "Invalid character h in position 2 in 1st $c in 040."
  }, {
    "tag" : "040",
    "errorLevel" : "CRITICAL",
    "message" : "Invalid character t in position 3 in 1st $d in 040."
  }, {
    "tag" : "040",
    "errorLevel" : "CRITICAL",
    "message" : "Invalid symbol NhCcYBP in 1st $c in 040."
  }, {
    "tag" : "040",
    "errorLevel" : "CRITICAL",
    "message" : "Invalid symbol CSt in 1st $d in 040."
  } ]
}

**Campus email addresses**
#1035
STF - SUL - datacontrol@stanford.edu
CASUM - Lane - tsallen@stanford.edu
RCJ - Law - law_cataloging@lists.stanford.edu
HIN - Hoover - hooverdescription@stanford.edu
S7Z - Business - sabbott@stanford.edu

**Comment by jermnelson** [comment]
@ahafele, I'm creating a web UI interface to the OCLC reports. Here is an example of the front-page (the actual reports are just stubs to illustrate how each report would be linked from front-page)
<img width="1112" alt="Screenshot 2024-07-31 at 12 46 38 PM" src="https://github.com/user-attachments/assets/ba225abc-b427-4b03-8a2a-d16be926e294">

Here is an example of the `mulitple_oclc_numbers` report from the UI. This URL would be provided in the emails sent to staff.
<img width="1043" alt="Screenshot 2024-07-31 at 12 20 16 PM" src="https://github.com/user-attachments/assets/ff645f3c-b4a9-4d50-8636-778c294eb282">

Any suggestions about this UI would be great! Thanks!

**Comment by ahafele** [comment]
This looks good so far! Will the UUIDs on the second screenshot link back to folio? We will also want to discuss who we give airflow access to in order to click the DAG run link.

**Comment by jermnelson** [comment]
Should not have been closed; re-opening as we need other reports

**Comment by ahafele** [comment]
@jermnelson I don't think logging is turned on for /worldcat/manage/institution/holdings/{oclcNumber}/set

**Comment by ahafele** [comment]
@jermnelson ~~I'm attaching a file of UUIDs~~ I'm putting in slack 2 files of UUIDs (won't allow csv upload here) for testing vi the UI upload while I'm on vacation. 
I have found that for the UI upload the use of new or update will work for all except records that are suppressed and should have holdings unset. That is in a separate del. file. 

b574ccdf-567a-5821-9259-533c686f3464 - should attempt to set holdings
17b75ed4-94e8-5e77-aada-f818fd9cc71d - has two oclc numbers and should report out per #1 above
16da5eed-69e7-46da-9d6d-6077543e3e01 - new record that will have errors
84521343-7b38-5150-a020-bf1d82d8e2d0 - new record that should pass as a match and might have new record errors

0cb6a16c-751e-5006-8a27-739eaa069917 - suppressed and should attempt to unset holdings. Response code 200 but message other than "Unset Holdings Succeeded." or "WorldCat Holding already unset." #3b above

**Comment by ahafele** [comment]
@jermnelson 
This record has more than one oclc number 17b75ed4-94e8-5e77-aada-f818fd9cc71d
In this dag run it is having the holdings set https://sul-libsys-airflow-dev.stanford.edu/dags/send_oclc_records/grid?run_id=manual__2024-08-20T16%3A16%3A48.210425%2B00%3A00&execution_date=2024-08-20+16%3A16%3A48.210425%2B00%3A00&tab=xcom&dag_run_id=manual__2024-08-20T15%3A57%3A14.882114%2B00%3A00&task_id=set_holdings_oclc_task
I don't know which OCLC number it set holdings for or how it decided which oclc number to use. 
It should be reported out per #1 in this ticket https://app.zenhub.com/workspaces/folio-at-stanford-628d6cab8c42a90248e5eb79/issues/gh/sul-dlss/libsys-airflow/1080 and emailed/made available under Multiple OCLC Numbers section you have in the UI https://sul-libsys-airflow-dev.stanford.edu/data_export_oclc_reports/#STF

Should I write up a bug ticket or is it just work that still needs to be done?

**Comment by ahafele** [comment]
Can you include logging for the set holdings task so I can see the response from OCLC? 
Something like 
{
  "controlNumber": "439887343",
  "requestedControlNumber": "439887343",
  "institutionCode": "158223",
  "institutionSymbol": "OCWMS",
  "success": true,
  "message": "Holding Updated Successfully",
  "action": "Set Holdings"
}

**Comment by ahafele** [comment]
Small changes needed 
UI - change **Set Holdings (After matching) Errors** to **Set Holdings (after matching) Errors**
Emails - Subject for Unset holdings errors should be **OCLC: Unset holdings error for SUL**
<img width="882" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEZ4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a86840f2b7f9a64cf6c0ff9b4c39cfd11b31be79/Screenshot%202024-08-20%20at%2011.34.23%E2%80%AFAM.png" alt="Screenshot 2024-08-20 at 11.34.23 AM.png" />

**Comment by jermnelson** [comment]
Hi @ahafele, looking at the MARC for [17b75ed4-94e8-5e77-aada-f818fd9cc71d](https://folio-test.stanford.edu/inventory/viewsource/17b75ed4-94e8-5e77-aada-f818fd9cc71d), there is only 1 OCLC number in subfield `a`, we don't check for any values in the subfield `z`. 

This record would not have been caught in the selection DAG as a "Multiple OCLC" error and would have been sent to the transmission DAG for setting the holdings value.

**Comment by ahafele** [comment]
Hi @jermnelson - yea I thought that might be happening so I tried again with two OCLC numbers that were both in $a b939118d-cd44-5ba0-83aa-f21a51e6f323 and still didn't see a report. Can you confirm that the work to report this as an error is already done?

**Comment by ahafele** [comment]
@jermnelson as I test more I'm not sure what on this ticket is work that is ready for testing? Can you confirm which of the 1-4b is ready to test?

**Comment by jermnelson** [comment]
Other than confirming the Multiple OCLC Numbers report 1, 2-4b should all be ready to test.
