### ISSUE TITLE
GOBI gap DAG run failed

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#1117]
Tried to run the select gobi dag from August '23 till now. it failed on fetch ids task. 

https://sul-libsys-airflow-stage.stanford.edu/dags/select_gobi_records/grid?run_id=manual__2024-07-23T19:32:18%2B00:00&execution_date=2024-07-23+19:32:18%2B00:00&tab=graph&dag_run_id=manual__2024-07-23T19:32:18%2B00:00

**Comment by jgreben** [comment]
We decided to split the date range up in two or three dag runs, or 3-4 months of data at a time.

**Comment by jgreben** [comment]
This was fixed when we ran it from 9/1 to present.
