### ISSUE TITLE
Load On-order Bibs

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#112]
We need to load bib records for On-order stuff. Some have items and some don't. All should have items in FOLIO. Darsi will create a tsv that will be used to generate Holdings _and_ an Item in FOLIO. (This excludes Electronic Resources that will not have items in FOLIO). 

TSV will have - 

- ckey
- call number type (@jermnelson will see if FOLIO will accept blank)
- basecallnum - likely blank (@dlrueda will see if there are examples that have call numbers and Alissa will review)
- volume info - likely blank
- barcode - blank
- homeloc
- curloc
- itemtype

@dlrueda here are some examples to generate data. Once done @jermnelson will test with current code to see if works. 

No items
- 14223817
- 14242913

Items
- 13500366
- 12213695
- ~~13583495~~ (2 copies with 1 on-order) Per Suzette this is a mistake. @dlrueda we only want to create FOLIO items if there is an open order attached. In this case there is not.

**Comment by thatbudakguy** [comment]
blocked on https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/110

**Comment by shelleydoljack** [comment]
This ticket is ready for SUL and LAW on-order bibs. Still need to figure out for Business Library, which @dlrueda was going to follow-up with Kent.

Files ready to load are in `/s/SUL/Dataload/folio_symphony_extract/Bibs_catdumps`. They begin with `ON-ORDER.*`.

**Comment by dlrueda** [comment]
the tsv file of items has no call number, no barcode.  It DOES have library, home location, and current location of ON-ORDER.  The current location on ON-ORDER should map to a FOLIO item status of “On order"

**Comment by dlrueda** [comment]
No temporary location needed.  Map permanent location from library and home location values.
