### ISSUE TITLE
Delete VMA files

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#1120]
From Monica/Jeanette
 
Would it be possible to delete all the fetched files from EBSCO Subscription Services (EBSCO-SUL) in VMA? (I don’t see any option in the interface to be able to delete them on my end.)
 
https://sul-libsys-airflow-prod.stanford.edu/vendor_management/vendors/1371
https://sul-libsys-airflow-prod.stanford.edu/vendor_management/interfaces/116
https://sul-libsys-airflow-prod.stanford.edu/vendor_management/interfaces/149
https://sul-libsys-airflow-prod.stanford.edu/vendor_management/interfaces/150

**Comment by jermnelson** [comment]
@ahafele all files have been deleted for these three interfaces.
