### ISSUE TITLE
OCLC export - not receiving multiple oclc number email

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#1194]
Multiple OCLC Identifiers email was in place as of 8/27. No longer receiving this email or seeing report in UI when testing file of UUIDs with multiple OCLC numbers.

**Comment by ahafele** [comment]
Example DAG run. https://sul-libsys-airflow-dev.stanford.edu/dags/select_oclc_records/grid?run_id=manual__2024-09-13T15:10:44.485233%2B00:00&execution_date=2024-09-13+15:10:44.485233%2B00:00&tab=graph&dag_run_id=manual__2024-09-13T15:10:44.485233%2B00:00

**Comment by ahafele** [comment]
Receiving email now but not seeing the report in the UI.

**Comment by jermnelson** [comment]
@ahafele - Would there ever be a situation where multiple OCLC numbers would exist in more than one library? If so, we'll need to change the structure of the reports so that we can generate and save the reports that span multiple libraries.

**Comment by ahafele** [comment]
@jermnelson do you mean a DAG run with 1 record from Law that has multiple OCLC numbers and 1 record from SUL that has multiple OCLC numbers? Yes, this can happen.
