### ISSUE TITLE
Investigate Capistrano Rake Task Improvements for Alembic migrations

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#1200]
With the PR [1195](https://github.com/sul-dlss/libsys-airflow/pull/1195) being merged, the Capistrano Rake tasks for Alembic migration tasks now are making two alembic calls, one each for VMA and Digital Bookplates databases. With the calls all being concatenated with `&&` making the logs hard to determine what migration is being run. It might be nice to run only the migration for specific database but also continue having a task that runs all of the migration. 

These are the implicated Rake tasks:
- [alembic:migration](https://github.com/sul-dlss/libsys-airflow/blob/64edb89156ba36d9ead08afd31630c08999ec3f2/config/deploy.rb#L77-L82)
- [alembic:current]( https://github.com/sul-dlss/libsys-airflow/blob/64edb89156ba36d9ead08afd31630c08999ec3f2/config/deploy.rb#L84-L89)
- [alembic:history](https://github.com/sul-dlss/libsys-airflow/blob/64edb89156ba36d9ead08afd31630c08999ec3f2/config/deploy.rb#L91-L97)

**Comment by jgreben** [comment]
Fixed by #1201
