### ISSUE TITLE
Branch off from ap_payment_report DAG a list of paid invoice UUIDs

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/libsys-airflow#1206]
The weekly ap_payment_report DAG has a task that retrieves the invoice UUIDs in folio and updates the status to "Paid." The [retrieve_invoice_task](https://github.com/sul-dlss/libsys-airflow/blob/b9e9008a775bb62b6fdf31442c56f744b66beacc/libsys_airflow/plugins/orafin/tasks.py#L183-L189) returns an invoice UUID for each row in the report. We want to branch off from here and send a list of invoice UUID's as a configuration parameter for a new DAG that will be "find instances paid on bookplate fund". This should also trigger this new DAG to run.

**Comment by jgreben** [comment]
UUIDs are in each mapped task from the [update_invoices_task](https://github.com/sul-dlss/libsys-airflow/blob/b9e9008a775bb62b6fdf31442c56f744b66beacc/libsys_airflow/plugins/orafin/tasks.py#L228) (Not the retrieve_invoice_task)

**Comment by shelleydoljack** [comment]
@jermnelson I was wondering if you could help confirm which task in the ap_payment_report DAG that will give us an invoice UUID that can be used as input for the DAG to get instances paid on bookplate funds. The XCOM for each retrieve_invoice_task has an invoice UUID and also the update_invoices_task. I see there is some code to check if the invoice is marked cancelled or paid in folio. Should we use the update_invoices_task XCOM to get the invoice UUID? Do we need to also get the invoice UUIDs for ones that are already marked as status paid in folio?

**Comment by jermnelson** [comment]
@shelleydoljack, I think that is right; we'll want to use the `update_invoices_task` invoices to get the invoices. It does make sense to also get the invoices that have already been marked paid in folio as well.

**Comment by shelleydoljack** [comment]
We decided to not do this.
