### ISSUE TITLE
Create a find instances paid on bookplate funds DAG

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/libsys-airflow#1207]
The scaffold of this DAG is outlined in the middle section of this diagram: https://docs.google.com/drawings/d/1H9PPL0u4AJxiE0gYmEKlaMTRrO5aUybSuOsRVMiV3eo/edit?usp=sharing

This ticket should just be to scaffold out the tasks outlined in the diagram. The DAG ~won't run on a schedule but will be triggered from the ap_payment_report DAG with a list of invoice UUID's as configuration, or triggered manually~ will run weekly tbd (in our previous process, we'd have this run just before data was refreshed from SDR) and should either get all instances paid on bookplate funds in folio (when the fund is new) or get instances paid on bookplate funds in folio since it last ran. Use the invoice paymentDate field to determine when paid.

**Comment by shelleydoljack** [comment]
A good example DAG that gets data is in the OraFin dags...

**Comment by jgreben** [comment]
@shelleydoljack  Is the list of invoice UUIDs that trigger this new DAG also in the oration files report?

libsys_airflow/plugins/orafin/tasks.py:
```
conf={
                "ap_report_path": f"{airflow}/orafin-files/reports/{report['file_name']}"
            },
```

**Comment by jgreben** [comment]
Is this the function to use to get all of the instances paid on bookplate funds in folio? https://github.com/sul-dlss/libsys-airflow/blob/67e3d9de5dcb975852c73a5d8656814d2d35baec/libsys_airflow/plugins/orafin/payments.py#L23

**Comment by shelleydoljack** [comment]
> Is this the function to use to get all of the instances paid on bookplate funds in folio?
> 
> https://github.com/sul-dlss/libsys-airflow/blob/67e3d9de5dcb975852c73a5d8656814d2d35baec/libsys_airflow/plugins/orafin/payments.py#L23

No, that function is used to get the external account number that is in the folio fund record to add it to the feeder file sent to University Accounts Payable.
