### ISSUE TITLE
Get po lines for each bookplate fund using paid invoice lines

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/libsys-airflow#1209]
The input of this task should be a list of paid invoice lines with a fundDistribution that contained a bookplate fund UUID. With the list of invoice lines, get the poLineId for each using the endpoint `/invoice/invoice-lines/<invoiceLineId>`. The output should be a list of po lines that were in the invoice lines that were paid with a bookplate fund and the associated fund_name. So maybe something like:
```
[
  {"ABBOTT": ['798596da-12a6-4c6d-8d3a-3bb6c54cb2f1', '7a5888fe-689b-4cfe-a27d-c2675a235203']},
  {"FUND_NAME": ['po_line_uuid', 'po_line_uuid']}
]
```

**Comment by jgreben** [comment]
What would a mock input look like for this task?

**Comment by shelleydoljack** [comment]
I think this task is not going to be separate from the previous task that is outlined in ticket https://github.com/sul-dlss/libsys-airflow/issues/1218. While working on this [branch](https://github.com/sul-dlss/libsys-airflow/tree/t1218-paid-invoices), I came to realize that this would take too long if we query the invoice-lines endpoint for each paid invoice UUID to get the invoice lines and then again to get invoice lines with a bookplate fund ID in the fundDistribution and then match where invoice lines in each set are a union. So this task will probably change, in that it would be getting po lines from a data structure returned in the previous task. Maybe even just a function to be used by the previous task. Maybe we can discuss in a pairing session.

**Comment by jgreben** [comment]
Pairing would be good because now I am confused by which task is "this task" and which is "the previous task".
