### ISSUE TITLE
OCLC Exports - add additional marc modifications for new records

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#1232]
After additional testing for New records and after discussions with OCLC support, Jeanette confirms that we need to make 2 additional edits to the MARC records before attempting to POST as new. These changes should only be in the record we post and should NOT be reflected back in our local FOLIO data. In previous OCLC processing these changes were made by OCLC when we sent them our records and are needed to conform to their standards. 

@jermnelson do we already have a pattern for this? I was thinking we did with stripping alpha characters from 001s but it looks like we are just removing the 001s all together. 

1. 040 
Change any occurrence of CSt  to STF

example
040	   	‡a CSt ‡b eng ‡e rda ‡c CSt 
becomes
040	   	‡a STF ‡b eng ‡e rda ‡c STF 

2. 007 
Change any blank to a fill character |

example 
007	cr un      
becomes
007	cr un|||||||||

**Comment by jermnelson** [comment]
@ahafele, a question about the 007 modification. Are the blanks to be replaced with "|" only after the last value in the 007? Would you be able to provide some more examples? Thanks!

**Comment by ahafele** [comment]
@jermnelson I think it should be any blank except position 00 or 02. (Probably most often this will be after the last value but I'll try and find outlier examples)

**Comment by ahafele** [comment]
Tested and this looks good!
