### ISSUE TITLE
Trigger the add 979 fields DAG from digital_bookplate_instances DAG

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/libsys-airflow#1238]
At the end of the DAG for finding instances paid on bookplate funds, we should trigger the next DAG, which will add 979 data to MARC tags. This task is currently in a WIP branch: https://github.com/sul-dlss/libsys-airflow/blob/5a91e11a77b976a1ecd5e5cc5fe9e91c0f5326d1/libsys_airflow/dags/digital_bookplates/digital_bookplate_instances.py#L62

We have a ticket for starting the add 979 fields DAG here https://github.com/sul-dlss/libsys-airflow/issues/1186 that details a bit what the output of this task should be.

The XCOM from the previous task (in ticket https://github.com/sul-dlss/libsys-airflow/issues/1210) should have a data structure that looks like this (instance ID as key and one or more bookplate as value):
```
{
 "242c6000-8485-5fcd-9b5e-adb60788ca59": [
  	{ "druid": "", "fund_name": "", "image_filename": "", "title": "" },
	…
 ]
}
```
We should use this data to trigger the next DAG with fund names and instances.

**Comment by shelleydoljack** [comment]
Each instance ID in the data should trigger a dag run.

**Comment by jgreben** [comment]
The XCOM from the previous task or the UI triggering the `digital_bookplate_979` DAG should pass the data as a param named `druids_for_instance_id`. This is the task that will be called from the `digital_bookplate_979` DAG:

```
@task
def launch_add_979_fields_task(**kwargs):
    """
    Trigger add a tag dag with instance UUIDs and fund 979 data. Returns a dict:
    "242c6000-8485-5fcd-9b5e-adb60788ca59": [
        { "druid": "", "fund_name": "", "image_filename": "", "title": "" },
        { "druid": "", "fund_name": "", "image_filename": "", "title": "" },
    ]
    """
    params = kwargs.get("params",{})
    return params.get("druids_for_instance_id", {})
```

**Comment by shelleydoljack** [comment]
Fixed in https://github.com/sul-dlss/libsys-airflow/pull/1355
