### ISSUE TITLE
Use workgroup to confine access to digital bookplates UI

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/libsys-airflow#1262]

**Comment by shelleydoljack** [comment]
The workgroup is called sulair:libsys-dig-bookplates

**Comment by shelleydoljack** [comment]
In standup this morning, Jeremy mentioned that this should be a puppet PR (access is controlled there and not through the flask app).

**Comment by jgreben** [comment]
https://github.com/sul-dlss/puppet/pull/new/jgrebenAddsWorkgroupAccessLibsysAirflow

**Comment by jgreben** [comment]
This should be in place now.

**Comment by jgreben** [comment]
I added all of us to sulair:libsys-dig-bookplates workgroup and verified that the puppet rule indeed restricts access.
