### ISSUE TITLE
Create and use workgroup for boundwiths UI

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/libsys-airflow#1263]
The UI for creating boundwith relationships should be only accessed by users in a workgroup, similar to VMA.

**Comment by dlrueda** [comment]
Workgroup sulair:libsys-boundwiths created  [operations-tasks #3627](https://github.com/sul-dlss/operations-tasks/issues/3627)

**Comment by jgreben** [comment]
Will be in place when https://github.com/sul-dlss/puppet/pull/11487 gets merged.

**Comment by jermnelson** [comment]
Closing as this functionality is in place.
