### ISSUE TITLE
Log messaging for trigger_instances_dag shows opposite of what happened?

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/libsys-airflow#1367]
On a test run of fetch_digital_bookplates with an empty digital_bookplates table, the task to trigger dag runs in digital_bookplate_instances for only funds that have fund uuid's worked, however the [log message for the task](https://sul-libsys-airflow-dev.stanford.edu/dags/fetch_digital_bookplates/grid?run_id=manual__2024-10-26T02%3A19%3A07.439057%2B00%3A00&execution_date=2024-10-26+02%3A19%3A07.439057%2B00%3A00&tab=logs&dag_run_id=manual__2024-10-26T02%3A19%3A07.439057%2B00%3A00&task_id=trigger_instances_dag) doesn't make much sense. It shows:

> [2024-10-26, 03:02:08 UTC] {purl_fetcher.py:201} WARNING - Should trigger 846 DAG runs
[2024-10-26, 03:02:08 UTC] {purl_fetcher.py:212} WARNING - Skipping new fund without fund uuid
[2024-10-26, 03:02:08 UTC] {purl_fetcher.py:212} WARNING - Skipping new fund without fund uuid
...
[2024-10-26, 03:02:34 UTC] {purl_fetcher.py:212} WARNING - Skipping new fund without fund uuid
[2024-10-26, 03:02:34 UTC] {python.py:202} INFO - Done. Returned value was: True

The total number of digital bookplates is 846 but only about 250 have fund UUIDs. The list of "WARNING - Skipping new fund without fund uuid" is 249 lines long. It seems maybe the opposite is reported?

**Comment by jgreben** [comment]
I commented out the TriggerDagRunOperator and added some additional logging and then cleared the task.
```
for i, fund in enumerate(new_funds):
        logger.info(f"HERE:{fund['fund_uuid']}")
        if fund["fund_uuid"] is not None:
            logger.info("Trigger new fund DAG")
            #TriggerDagRunOperator(
            #    task_id=f"new-instance-dag-{i}",
            #    trigger_dag_id="digital_bookplate_instances",
            #    conf={"funds": [fund]},
            #).execute(
            #    kwargs  # type: ignore
            #)
        else:
            logger.warning("Skipping new fund without fund uuid")
```

Then I searched the logs and got:
```
$ grep 'HERE:None' ~/Desktop/debug.log | wc -l
     590
$ grep 'Skipping new' ~/Desktop/debug.log | wc -l
     590
$ grep 'Trigger new fund DAG' ~/Desktop/debug.log | wc -l
     256

```
¯\_(ツ)_/¯

**Comment by shelleydoljack** [comment]
Ahh thanks for checking. I went back and clicked "Download" for the log for attempt 1 and I'm seeing more data in that downloaded log file than what displays in the UI. When I filed the ticket, I copied what I saw in the UI. So the UI Log doesn't show the whole log file. Learn somthing new everyday I guess.
