### ISSUE TITLE
Select DAG

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#1439]
Note: account for Initial selection and ongoing (separate DAG?), should include option for date range configuration

Selection Criteria:
Initial
- All libraries, ~~excluding Lane~~
- New Bib records
- Instance status term = Cataloged
- Cataloged date = real date (not empty)
- Unsuppressed at Instance level
- Using specified timeframe, e.g. since FOLIO migration
- No deletes
- No updates

Ongoing
- All libraries
- New cataloged Bib records since last run
- Instance status term = Cataloged
- Cataloged date = real date (not empty)
- Unsuppressed at Instance level
- No deletes
- No updates

Record processing:

Exclude records with 
915 |aNO EXPORT|bAUTHORITY VENDOR
or
590 |a MARCit brief record.

**Comment by ahafele** [comment]
Add Campus as a variable so we can e.g. send only Law library records.

**Comment by shelleydoljack** [comment]
Do we know the schedule for the backstage selection? (weekly, daily, etc?) And are we sending marcxml files or marc files (the answer is dependent upon whether we are sending holdings and items)? I'm guessing just bib marc and no holdings info, right?

**Comment by dlrueda** [comment]
Just bib Marc for export.  No holdings and items needed.

**Comment by ahafele** [comment]
Marc files and weekly schedule.

**Comment by shelleydoljack** [comment]
So... the exclude 915 criteria, is that correct? I was looking at what [we're doing in general](https://docs.google.com/document/d/1NAbY9L6G16DItIBjtRQKFDcL6NN5cWK8VfsFCT48vTA/edit?tab=t.0#bookmark=id.6qgq6atdxc1p) and realized it's not the same for this. Should it be both `|bFOR SU ONLY` and `|bAUTHORITY VENDOR`?

**Comment by ahafele** [comment]
Only exclude if the 915 contains both |aNO EXPORT and |bAUTHORITY VENDOR

**Comment by ahafele** [comment]
Update based on meeting with Backstage - we can leave Lane's records in the initial file.

**Comment by shelleydoljack** [comment]
Since we don't need to exclude Lane from the initial file, I _think_ we said at standup that we won't make the campus configurable, until we need to. Is that correct, or am I misremembering?

**Comment by ahafele** [comment]
That is correct.
