### ISSUE TITLE
add_bw_relationships DAG failing silently

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#1447]
The most recent example is a DAG run that fails on the `add_bw_record `task but no email is generated so the user doesn't know what happened - in this case they alerted us because no summary email was generated. 

https://sul-libsys-airflow-prod.stanford.edu/dags/add_bw_relationships/grid?run_id=manual__2024-11-19T21%3A46%3A51.433639%2B00%3A00&execution_date=2024-11-19+21%3A46%3A51.433639%2B00%3A00&tab=graph&dag_run_id=manual__2024-11-19T21%3A46%3A51.433639%2B00%3A00&task_id=add_bw_record

**Comment by ahafele** [comment]
I'm also not sure why this one is failing and there is no log for clues. I was able to add it manually through the UI.

**Comment by jermnelson** [comment]
Yes, the column headers come from the uploaded csv file.

**Comment by jermnelson** [comment]
Should be fixed in PR #1456
