### ISSUE TITLE
Update emails for Fix Encumbrance script DAGs

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#1469]
[Law](https://sul-libsys-airflow-prod.stanford.edu/dags/fix_encumbrances_law/grid) - acquisitions@law.stanford.edu
[Lane](https://sul-libsys-airflow-prod.stanford.edu/dags/fix_encumbrances_lane/grid) - adlpr@stanford.edu
[SUL](https://sul-libsys-airflow-prod.stanford.edu/dags/fix_encumbrances_sul/grid) - scaneda@stanford.edu

**Comment by jgreben** [comment]
Done. See https://sul-libsys-airflow-prod.stanford.edu/variable/list/

**Comment by ahafele** [comment]
@jgreben not sure this is working. Users did not receive the emails today's DAG runs.
