### ISSUE TITLE
Use dynamic item note type for Notes

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#152]
See ticket [Item records do not have item extended info notes](https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/168)

**Comment by jermnelson** [comment]
Per discussion in 9/23 stand-up, `circnotes.tsv` and `circstaff.tsv` should be mapped to Item "Circ Staff" note type.

**Comment by jermnelson** [comment]
Also need to add HVSHELFLOC as a note type, see [170](https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/170)

**Comment by dlrueda** [comment]
the file is `circnote.tsv` (not circnotes.tsv as in above comment)
