### ISSUE TITLE
Create a new column for "HOLDINGS_HRID"

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/libsys-airflow#175]
Create a new column for "HOLDINGS_HRID" and retain the original "CATKEY". This change might make it easier to troubleshoot when we run into issues about items getting on the wrong holdings.
https://github.com/sul-dlss/libsys-airflow/blob/387ab8fbd3cfae8050590707c7a27c3e9f33ba01/plugins/folio/helpers/tsv.py#L164

**Comment by jermnelson** [comment]
After running this code for folio-test migration loads, we should replace the pandas dataframe operations with maybe using the built-in csv library as it is taking this task close to 20 minutes for large tsv files (150+ rows)

**Comment by jermnelson** [comment]
Closing, no longer using this approach with #176 being merged.
