### ISSUE TITLE
Handle boundwiths as post-migration dag

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-airflow#187]
Ticket is a placeholder until we figure out what bound with data from Symphony will look like.  

Dag will need to create the links between parent and child instances (and/or holdings and/or items) in FOLIO.

**Comment by shelleydoljack** [comment]
To create a bound-with relationship between the item and holding record, you use the `POST /inventory-storage/bound-with-parts` endpoint with the holdingsRecordId of the BW-CHILD and the itemId of the BW-PARENT, example:
```
{
  "holdingsRecordId": "49f9c0db-161e-5bb9-a600-7c55fac49f3f",
  "itemId": "d6d1aa74-31c8-5c03-bda5-582b15155f5e"
}
```

**Comment by shelleydoljack** [comment]
Tested trying to post to the endpoint with an item UUID that doesn't exist yet in folio and it errors out.
```
{
    "errors": [
        {
            "message": "Cannot set bound_with_part.itemid = a89be179-0ee5-4117-a51a-5e804c4243ec because it does not exist in item.id.",
            "type": "1",
            "code": "-1",
            "parameters": [
                {
                    "key": "bound_with_part.itemid",
                    "value": "a89be179-0ee5-4117-a51a-5e804c4243ec"
                }
            ]
        }
    ]
}
```
So posting to folio the bound-with relationships would likely need to be done after all the bibs and items are migrated.

**Comment by ahafele** [comment]
In Nolana you can now set the Holdings Type as bound-with. This is desirable for us. Could this happen here as well or should I write a new ticket? @jermnelson thoughts?

**Comment by jermnelson** [comment]
I think that is doable in this post-migration DAG

**Comment by jgreben** [comment]
Needs discussion:
- deterministic holdings uuid generation based on data in tsv not incremental hrid
- deterministic items uuid based on barcode OR ckey, but not concatenation of both.
- library and location of BW child: needs adding to locations.tsv (and in folio)?

**Comment by shelleydoljack** [comment]
@jgreben Alissa wants us to create a holdings record with type = bound-with. @ahafele which holdings record in folio should get type=bound-with? The holdings record of the principal (BW-PARENT) or the part (BW-CHILD)? Also, there doesn't appear to be a bound-with relationship holdings type: https://folio-dev.stanford.edu/settings/inventory/holdingsTypes

**Comment by ahafele** [comment]
I just went back and checked the the holdings type Bound-with is supposed to come with Nolana, but I don't see it in snapshot either so I don't know. I think we can just add it ourselves. The part (BW-CHILD) should get the holdings type = Bound-with. I don't think the parent should get it because it might have items that are not bw. I'll confirm with MD tomorrow.
