### ISSUE TITLE
Provide Search for FOLIO Reports

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#205]
Right now there isn't a way to search the FOLIO transformation reports for any **FIX BEFORE MIGRATION** notes through the UI. We should provide a simple search box searches the full-text of the reports for phrases like this to assist in migration remediation.

**Comment by jermnelson** [comment]
@ahafele I ran a search using grep on the server on Friday and didn't find any instances of bib records in the **FIX BEFORE MIGRATION** category for the full migration load to folio-test. This took a couple of hours and I am suspicious about this result but I haven't looked at the code to see what conditions in the `folio_migration_tools` would write a message to this report.

**Comment by ahafele** [comment]
Hmm that is suspicious and Vitus was also thinking that would be odd. When you have a chance to look at what conditions write the message I'll be curious to know. Thanks.
