### ISSUE TITLE
Shadowed locations in Symphony, to be suppressed at item level in FOLIO

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#226]
From this [comment](https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/273#issuecomment-1439036599), set `discoverySuppress` for the Item records if they have any of the following current or home locations (ignore that they are in various sections, that’s for Darsi to keep straight that mappings need to be created for some of them):
- [ ] WITHDRAWN 
- [x] MANNING
- [x] INSTRUCTOR
- [x] SEL-NOTIFY (current loc)
- [x] CDPSHADOW
- [x] TECHSHADOW
- [x] STAFSHADOW
- [ ] SHADOW
- [x] MISS-INPRO
- [ ] LOST
- [ ] DISCARD
- [x] SPECM-S
- [x] SPECA-S
- [x] SPECB-S
- [ ] SPECMED-S (asked Spec staff about this on 3/13)
- [x] LOST-CLAIM
- [ ] EAL-TEMP-S (asked Charles about this on 3/13)
- [ ] LOST-PAID
- [ ] E-ORDER-S (asked Suzette about this on 3/13)
- [x] LOCKSS (asked Alissa about this on 3/13)
- [ ] SALDCPROJ2 (asked Vitus about this on 3/13)
- [ ] SALDCPROJ1 (asked Vitus about this on 3/13)

These are the exceptions.  Do NOT want to set these items to suppressed
FED-DOCS-S
SSRC-FIC-S

No items in this loc, fine to have any items with this home or current location marked as suppressed.  No mapping will be done. But if an item ends up having one of these locs, it should be suppressed.
BENDER-S
RESV-URL
POPUPLIB
3FL-REF-S
NEG-PURCH
TECH-UNIQ
SPECMEDX-S
SSRC-SLS
SPECAX-S
SPECBX-S
SPECMX-S
E-REQST-S
E-INPROC-S
INSHIPPING
W7-STFSHD
COLDSTOR
MAPFILE-S
MAPCASES-S

Won’t migrate items with this location
BASECALNUM
EDI
LOCKSS

_Originally posted by @dlrueda in https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/273#issuecomment-1439036599_

**Comment by jermnelson** [comment]
@dlrueda - Do these locations need to be added to FOLIO?

**Comment by dlrueda** [comment]
The list above is the Symphony location.  INSTRUCTOR maps to GRE-INSTRUCTOR, SCI-INSTRUCTOR etc.  So do you need a list of FOLIO locations that need to be suppressed, or Symphony locations (or maybe Symphony library/location combinations)?

**Comment by dlrueda** [comment]
These locations will be current locations only, and should not map to any FOLIO location. The home location should dictate the FOLIO location.  But if one of these locations is in the current location field, the item should be suppressed from discovery.

SEL-NOTIFY
MISS-INPRO
LOST-CLAIM
