### ISSUE TITLE
Circ Rule Matching on Last Winner instead of First Winner

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#232]
Because the circulation rules API like [/circulation/rules/loan-policy-all](https://s3.amazonaws.com/foliodocs/api/mod-circulation/p/circulation-rules.html#circulation_rules_loan_policy_all_get) returns the matching loan policies in decreasing priority, we need to match the winning policy on the first match instead of the last match.

**Comment by michelleif** [comment]
I tested single condition and a batch and it looks good to me
