### ISSUE TITLE
Create a Scaffold for a Daily Airflow DAG for retrieving dynamic list of MARC BIB records from various vendors

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#247]
Create an Airflow DAG that runs daily and queries the Dataloader Management App and possibly FOLIO [Organizations](https://dev.folio.org/reference/api/#mod-organizations-storage)  for a dynamic list of vendors that includes connection information (FTP, SFTP, username, passwords) and Data Import Profile for MARC BIB records along with specific pre- and post- processing tasks to be preformed on these records. 

This ticket should trigger secondary DAGs for each vendor load. 

Specific tasks to be accomplished will be ticketed separately.

**Comment by jmartin-sul** [comment]
this ticket would be complete if a skeleton DAG with the right placeholder tasks is created, with task implementation TBD based on dataloader management app API.

**Comment by jmartin-sul** [comment]
* on a daily basis, queries the data management app.
* gets back a list of vendors
* vendors have a list of interfaces (connection info and creds for e.g. FTP to remote system for data load files to retrieve)
* this app retrieves those interfaces
* for each interface, trigger a DAG that loads data from that vendor.

**Comment by jermnelson** [comment]
For this ticket, just create placeholder Tasks using the [EmptyOperator](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/empty/index.html) that can be replaced with  [PythonOperators](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/python/index.html#airflow.operators.python.PythonOperator) once those tickets are implemented.

**Comment by jermnelson** [comment]
Here are the follow-up tickets:

- https://github.com/sul-dlss/libsys-airflow/issues/279
- https://github.com/sul-dlss/libsys-airflow/issues/280
- https://github.com/sul-dlss/libsys-airflow/issues/281
