### ISSUE TITLE
Analysis of current DAGs/Plugins for Data Management Uploads

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#248]
Analysis of the current structure of the libsys-airflow's code base and how it supports upcoming DAGs for the Data Management. Should consider Airflow best practice and other Airflow work done in DLSS. May include follow-up tickets to refactor current libsys-airflow code based on this analysis.

## Links
- [Airflow Best Practices](https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html)
- [DLME Airflow](https://github.com/sul-dlss/dlme-airflow)
- Sinopia's [ILS Middleware](https://github.com/ld4p/ils-middleware)

**Comment by jmartin-sul** [comment]
will determine necessary refactoring as we get into other tickets, closing this for now
