### ISSUE TITLE
Airflow Task: File naming Pre-processing

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#263]
After a file has been downloaded from a vendor site or uploaded by staff member, extracted if contained in a [zip file](https://github.com/sul-dlss/libsys-airflow/issues/262), the file's name may need to modified based on the following (from the [Vendor data processing](https://docs.google.com/document/d/11JzLJb9kbW4u3dDLZ9_oFtsRtmnPkl0laS4zigQh5X0/edit#) document):

- [ ] Casalini TOC PDFs - Remove `()` in filenames
- [ ] OCLC - Remove `metacoll.stf` and `.wcholdings`

There may be other vendor files that need future naming modifications, not sure if these need to be pulled from the Vendor Management App or could added as needed by libsys staff.

**Comment by jmartin-sul** [comment]
@ahafele says we don't need this for the 6 priority vendors.  @jermnelson says casalini PDFs may be needed for searchworks?  requirements unclear at this point, maybe needed, so keeping open and backlogged for now.

**Comment by ahafele** [comment]
Closing until we are ready for casalini toc/oclc work.
