### ISSUE TITLE
Airflow Tasks: MARC Bibs Modification before loading

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#264]
Before loading a Vendor MARC BIB file, the following modification need to occur:

- [ ] Move/Change MARC 505 to MARC 905 fields
- [ ] Move/Change MARC 520 to MARC  920 fields
- [ ] Remove any new line characters in the MARC (@ahafele should this check all MARC fixed and variable fields?)
- [ ] Remove the following fields:
    - [ ] 905
    - [ ] 920
    - [ ] 986
- [ ] Save MARC record as the UTF8 encoding

**Comment by ahafele** [comment]
@jermnelson The first two (505 and 520) are specific to the vendor Amalivre and should not be done on all records. 
I'll look into the newline question.

**Comment by ndushay** [comment]
Noting that PR #340 addressed issue #319, which was to remove 905, 910 and 920 fields.  Noting further that the code in PR #340 moved to a different file in PR #351.

All to say ... is this done?

**Comment by aaron-collier** [comment]
Yes, this is closable. There will be another ticket for the move task.
