### ISSUE TITLE
[SPIKE] Lehigh App for Orders Requirements Analysis

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#271]
Currently FOLIO's mod-data-import does not support creating and loading Order records from BIB 9xx fields. One option is the Lehigh's [FOLIO Order import tool](https://github.com/folio-labs/folio-order-import-tool). This tool is a Java standalone web application that may be difficult to integrate with Airflow as there doesn't appear to be an API that we can use. Also, the app creates Instances, Holdings, and Items records and we want to leverage `mod-data-import` to this FOLIO record creation. 

The scope of this Spike is to determine if Lehigh tool can be used in the context of Airflow and our planned use of the `mod-data-import`. If that doesn't look viable, create one or more tickets outlining what information needs to be extracted from the MARC Bib record 9xx fields to create Order records. Documentation in the FOLIO Wiki, [Import Orders in MARC format](https://wiki.folio.org/display/DD/Import+Orders+in+MARC+format), can be of use as it outlines future workflow for Orders importing using the `mod-data-import`.

Another source for requirements is FOLIO-FSE's [Order transformer](https://github.com/FOLIO-FSE/folio_migration_tools/blob/main/src/folio_migration_tools/migration_tasks/orders_transformer.py) that creates Order records from TSV files and the example [composite order mapping](https://github.com/FOLIO-FSE/migration_example/blob/main/mapping_files/composite_order_mapping.json).

Finally, the Okapi [mod-orders](https://dev.folio.org/reference/api/#mod-orders) and [mod-orders-storage](https://dev.folio.org/reference/api/#mod-orders-storage) provide the JSON schema for composite orders records.

**Comment by ndushay** [comment]
THIS TICKET:  Analysis of what's available - maybe indicate in ticket.  Would expect other tickets to come out of this if Lehigh app is promising.

**Comment by jermnelson** [comment]
Closing this ticket as our current thinking is that we may use the Lehigh tool as an interim solutions for Orders until we migrate to Orchid.
