### ISSUE TITLE
Breakout requirements for production Docker Images

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#274]
Currently we're including dev dependencies in our Docker environment when building with our default image from  https://github.com/sul-dlss/libsys-airflow/blob/631242e90fd5936baa6d2e33af5a2b8f1f74f1eb/Dockerfile#L13-L15.

**Comment by jmartin-sul** [comment]
We may want to have separate image builds for dev and prod.

poetry may have some facility for this like bundler does.

Research on options here is actionable, but implementation might be blocked by the poetry ticket.
