### ISSUE TITLE
User airflow Update

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#278]
Change the default password for the `airflow` user in both sul-libsys-airflow-dev.stanford.edu and sul-libsys-airflow-prod.stanford.edu and store the credentials in shared_configs. If/when ticket #5 is implemented, this user can removed and the shared_configs updated. **NOTE** since we're using docker-compose to deploy these environments, the airflow user password will need to be reset each time a branch is redeployed.

**Comment by aaron-collier** [comment]
@jermnelson this ticket is suggesting putting the credentials in shared_configs, but as it impacts deployment, I think it may make more sense to put them in vault, then puppet can be updated to set these as environment variable and docker-compose can use them from the environment to set on the container(s).

Does that make sense or am I misunderstanding the ticket?

**Comment by jermnelson** [comment]
@aaron-collier, I like your suggestions to use vault instead of shared_configs with credentials being propagating through to Docker's environmental variables.

**Comment by jmartin-sul** [comment]
We should let people in the channel know when this is changed, so no one is confused as to why the login no longer works.

Will probably go away once SSO is in place, but this is a much quicker change than implementing SSO, so not much wasted work.

**Comment by lwrubel** [comment]
- [ ] Put `airflow_password` in vault for dev and prod at:
```
puppet/application/folio/dev/airflow_password
puppet/application/folio/prod/airflow_password
```
- [ ] Change account's password via UI for prod
- [ ] Change account's password via UI for dev
- [ ] Update README with where to get the admin password
