### ISSUE TITLE
Airflow Task: Query Data Loading Management App

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#279]
On a daily schedule (maybe in the late afternoon) create a task for querying the Data Loading Management for a list of Vendors and Vendor Interfaces along with any extra information (filename patterns, etc. TBD) along with a list of pre-processing tasks. This payload should be parsed and pushed to XCOM variables for later downstream task consumption. 

This task could use the following Airflow components:
- [HTTP Connection](https://airflow.apache.org/docs/apache-airflow-providers-http/stable/connections/http.html) - store and management connection information to the Data Loading Management App
- [HTTP Sensor](https://airflow.apache.org/docs/apache-airflow-providers-http/stable/operators.html#httpsensor) Determine if the Data Loading Management app is available 
- [HTTP Operator](https://airflow.apache.org/docs/apache-airflow-providers-http/stable/operators.html#simplehttpoperator) Retrieve the JSON Payload from the Data Loading Management App

Possible helpful [article](https://betterdatascience.com/apache-airflow-rest-api/)

**Comment by aaron-collier** [comment]
Moving to backlog until unblocked.

**Comment by aaron-collier** [comment]
We are going a different direction and will not be using an external API
