### ISSUE TITLE
Trigger Dynamic DAG for Vendor Interface Task

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#281]
After retrieving all [Vendor Interfaces](https://github.com/sul-dlss/libsys-airflow/issues/280), trigger multiple DAGs for each Vendor Interface using the [TriggerDagRunOperator](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/trigger_dagrun/index.html).

**Comment by aaron-collier** [comment]
Closing in favor of tickets for the redesign.
