### ISSUE TITLE
Secure connections

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/libsys-airflow#297]
So that they are stored encrypted. See https://airflow.apache.org/docs/apache-airflow/1.10.12/howto/secure-connections.html

**Comment by jmartin-sul** [comment]
following the instructions [here](https://airflow.apache.org/docs/apache-airflow/2.5.3/administration-and-deployment/security/secrets/fernet.html#security-fernet), which were linked from [the docs that @jermnelson linked to](https://airflow.apache.org/docs/apache-airflow/2.5.3/howto/connection.html#security-of-connections-in-the-database), i generated a new fernet key for each airflow env (from my local libsys-airflow dev env), and stored them in vault under the `puppet/application/libsys_airflow/ENV/fernet_key` paths (where `ENV` is `dev`, `stage`, or `prod`).

i also submitted a [puppet PR](https://github.com/sul-dlss/puppet/pull/9436) to put the fernet key in a host VM env var (merged by rob this morning).

i also put in a PR against this repo (#306) to pass through the env var from the host OS to the docker containers via the docker-compose file (still needs review/merge).

i did all this from reading the docs, but i couldn't find a way to actually test it or confirm that there's a problem.  i didn't see any relevant errors or warnings when i started airflow via docker compose locally, and i didn't see any connection info at all in the airflow console in dev or prod (perhaps i don't have the necessary perms for that).  but from the docs, this seemed like the way to set this up, so hopefully i haven't been barking up the wrong tree.

**Comment by jmartin-sul** [comment]
TODO:
- [ ] get the docker compose PR reviewed and merged (#306)
- [ ] figure out whether it's necessary to follow the key rotation instructions given in the airflow docs.  it was unclear whether this procedure was needed when going from no fernet key to the first fernet key, or only when going from one non-empty fernet key to a different key.  see [here](https://airflow.apache.org/docs/apache-airflow/2.5.3/administration-and-deployment/security/secrets/fernet.html#rotating-encryption-keys).

**Comment by justinlittman** [comment]
It works!
![image.png](https://images.zenhubusercontent.com/5d8270f64def500001d12f23/da824889-e9ce-4c41-a34a-80073af3c9b9)

**Comment by justinlittman** [comment]
I tried the key rotation directions locally going from unencrypted to encrypted -- it didn't work. If we feel the need to encrypt keys, the existing connections can be deleted and re-created.
