### ISSUE TITLE
Airflow Connection Management for Vendor Interfaces

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#298]
As required by #261, for each Vendor's Interface, we need to have a corresponding Airflow Connection that contains the host and login credentials. With the FOLIO Interface record being the "source-of-truth", we need to:

- Check if an Airflow Connection already exists for the vendor Interface 
- Create a new Airflow Connection if doesn't
- Update an existing Airflow Connection if the Vendor Interface changes

See https://stackoverflow.com/questions/51863881/is-there-a-way-to-create-modify-connections-through-airflow-api

**Comment by ndushay** [comment]
Is this connection going to be created just-in-time for running a vendor's dag, including getting the latest info on vendor login from the FOLIO Interface record

OR

is it something that will be created once when airflow spins up, or under other circumstances 

OR

is there some other model in mind of what will trigger this code being used?
