### ISSUE TITLE
Add airflow python client to dependencies

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/libsys-airflow#318]
Install the airflow python client and ensure it is in the dependency list: https://github.com/apache/airflow-client-python

**Comment by edsu** [comment]
Just a heads up to be careful not to add it to the main dependencies or else dependency updates may pull in a more recent airflow than what is defined by the Docker image.

**Comment by mjgiarlo** [comment]
@aaron-collier @edsu It looks like airflow 2.5.3 is in the app's test deps, but the newest airflow-client is 2.5.1. I can't say whether the 2.5.1 version of the client will work with the 2.5.3 API. I can add it, though, so we can find out. (Is it concerning that the python client doesn't seem to keep pace with airflow? Alternative: we could bump airflow back to 2.5.1.?)

**Comment by aaron-collier** [comment]
@mjgiarlo i wonder if the version number is supposed to indicate parity or if we should be worried about it?

**Comment by mjgiarlo** [comment]
@aaron-collier 💬 
> @mjgiarlo i wonder if the version number is supposed to indicate parity or if we should be worried about it?

FWIW, here's the chronology of client and airflow releases:
* 12/02: server v2.5.0
* 1/20: client v2.5.0
* 1/20: server v2.5.1
* 1/29: client v2.5.1
* 3/15: server v2.5.2
* 4/1: server v2.5.3

They appear related to me, but I don't know if we should we worried. It's hard to judge without more context in this issue around what functional requirement(s) it's supporting. I can make the mechanical change, for sure.

**Comment by mjgiarlo** [comment]
Looking at the airflow 2.5.2 and 2.5.3 release notes, it looks like the 2.5.1 client should work with 2.5.3. There is a change in 2.5.2 that affects very specific date params are parsed, but 🤷🏻‍♂️
