### ISSUE TITLE
Establish Vendor Management plugin in airflow menu and initial vendor list

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/libsys-airflow#332]
Using https://github.com/sul-dlss/libsys-airflow/pull/331 as an example of extending the airflow dashboard menu to include a flask based plugin:

- [x] Add a "Vendor Management" menu to airflow
- [x] Add initial vendor list (screenshot example below, queried from folio organizations) that includes vendor name, code, id, and acquisitions unit. 
- [ ] Vendor list is paged and searchable by name and code

This initial page is complete when the vendor list displays all organizations in folio, linking to configuration and history pages will be addressed in followup tickets. The status, last scheduled job, and buttons in the example below should _**not**_ be included.

<img width="1466" alt="Screenshot 2023-04-25 at 8 41 45 AM" src="https://user-images.githubusercontent.com/2294288/234331857-4af51d7c-9205-4382-a30d-360614fb9814.png">

**Comment by lwrubel** [comment]
A few questions:
* The mockup shows the menu item as "Data Loading Management" but the text requests "Vendor Management". Which one should be used? I would use the same wording in naming the plugins directory. 
* Should the result of getting the organizations from FOLIO be written to the database (which is still in progress?). I think the answer is yes, but wasn't sure if that should also be included with this. 

I think it might be worth splitting the content of the Vendors page into a separate ticket.

**Comment by lwrubel** [comment]
Based on conversation with Aaron, will use Vendors Management as the naming throughout and will break up into multiple PRs.

**Comment by lwrubel** [comment]
As the ticket requests, I'm querying the live FOLIO for the needed organizations. But I think this is temporary, until the database and the vendors table is set up to serve as the source of organizations here? I am trying to figure out how much I should be testing the interaction with FOLIO.
