### ISSUE TITLE
Initialize file model for tracking vendor data load status and history

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/libsys-airflow#334]
Using ~~https://github.com/sul-dlss/libsys-airflow/pull/329/files~~ PR #333 as an example, initialize the "files" model based on https://docs.google.com/document/d/1xjbxiFWHT3THgaYC6mP1MS6VKoQKA2GWKey1TE0Y5cE/edit#heading=h.6qi50lyx2uxz

(db entity diagram at https://github.com/sul-dlss/libsys-airflow/wiki/Vendor-Load:--Database-Model)

This model is required to capture filenames from vendors with size and date attributes to determine when a file is "new" or has been loaded.

- [ ] Add files model under the data management plugin
- [ ] Update readme (or wiki) to include how to use the model with local database vendor_interface id to determine if a file is new

**Comment by ndushay** [comment]
is this table "files" or "file" ?

**Comment by ndushay** [comment]
@aaron-collier this ticket needs to have a ticket split out:  "Update readme (or wiki) to include how to use the model with local database vendor_interface id to determine if a file is new"
