### ISSUE TITLE
Investigate and document using flask_migrate or alembic for database initialization/migration

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/libsys-airflow#337]
https://flask-migrate.readthedocs.io/en/latest/

Flask migrate looks like a useful tool to implement rails like database migrations for a flask app. Using https://github.com/sul-dlss/libsys-airflow/pull/346 as an example of models we will implement, investigate implement using flask_migrate to:

- [ ] initialize the database for the vendor management app
- [ ] establish the basic vendor model and create the table
- [ ] document in the README the flask/flask_migrate commands that developers will use to initialize the vendor management database for local development
- [ ] determine how (or if) we can automate flask_migrate based database migrations on deployment

Alternatively investigate using Alembic (https://alembic.sqlalchemy.org/en/latest/autogenerate.html) which I think flask-migrate is based on.

**Comment by edsu** [comment]
I just wanted to note that I think the work on #346 is addressing this in part?
