### ISSUE TITLE
Airflow Task: Archive downloaded vendor data

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/libsys-airflow#338]
Create an airflow task for copying downloading vendor data into the archive path.

Follow the pattern established in DLME for reusable task code: https://github.com/sul-dlss/dlme-airflow/blob/main/dlme_airflow/tasks/harvest.py

This task module should take the configuration JSON as a parameter and using the provided vendor_uuid and interface_uuid, copy any new files from **{data_loader_path}/{vendor_uuid}/{interface_uuid}** *to* **{data_loader_archive_path}/{yyyy}{mm}{dd}/{vendor_uuid}/{interface_uuid}**.

This task is complete when:
- [ ] a task module (i.e. .../libsys-airflow/libsys_airflow/tasks/archive.py) exists
- [ ] the task module returns a PythonOperator that can be included in a DAG
- [ ] the task uses the config JSON payload to compare files in the data loader path with the archive path and copy any "new"* files into the archive.
- [ ] task task code has sufficient test coverage

Notes: 
- For the initial iteration of this task, it is expected that any files that do not exist in the source directory are copied to the archive directory.
- The files are saved to **{data_loader_archive_path}/{vendor_id}/{interface_id}** where data_loader_archive_path comes from the env (this will be /dataloader/archive on the server(s)), vendor_id and interface_id come from the config. If the directory does not exist, create it.
- It may be worthwhile, but not required, to look into adding a command line utility for running this task individually during development (https://github.com/sul-dlss/dlme-airflow/blob/main/bin/post-harvest)

**Comment by ndushay** [comment]
"For the initial iteration of this task, it is expected that any files that **do not exist in the source directory** are copied to the archive directory." ... uh ...   should that read any files in the source directory will be copied???
