### ISSUE TITLE
Add a base development DAG to verify and test tasks

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/libsys-airflow#341]
It would be very useful to have a base DAG (or possibly multiples) that we can use to verify the task code functions as expected and we can establish a pattern for interacting with the DAGRun configuration, XCOM return values, etc.

Initially, this could just be a simple dag that takes an example config (GOBI would be best) and executes the `marc_filter` task. The DAGRun would need to be manually initialized with a config:

```
{
  'vendor_name': 'GOBI/YBP', 
  'vendor_code': 'YANKEE-SUL',
  'vendor_uuid': '9cce436e-1858-4c37-9c7f-9374a36576ff',
  'vendor_interface_uuid': '65d30c15-a560-4064-be92-f90e38eeb351',
  'dataload_profile_id': 'TBD',  # uuid if this refers to folio
  'remote_path': 'oclc',
  'filename_regex': '^\d+\.mrc$'
}
```

Note: the above are the actual IDs for this particular GOBI interface, so should be sufficient for most of our initial testing as this is our first vendor to focus on.

Tasks:
- [ ] Establish a simple DAG that uses a fixture file to execute the `marc_filter` task
- [ ] Document in a wiki page or the README how to run the sample DAG with the above config

**Comment by aaron-collier** [comment]
Working on this in conjunction with #250 may be best to establish the FTP task as well...

**Comment by jmartin-sul** [comment]
closing this ticket as obsolete, we're past needing this example DAG, and are now connecting things in real DAGs
