### ISSUE TITLE
Initialize file_part model to track cocina manageable sizes of split files

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/libsys-airflow#347]
Using ~~https://github.com/sul-dlss/libsys-airflow/pull/329/files~~ PR #368 as an example, initialize the "files" model based on https://docs.google.com/document/d/1xjbxiFWHT3THgaYC6mP1MS6VKoQKA2GWKey1TE0Y5cE/edit#heading=h.6qi50lyx2uxz

(db entity diagram at https://github.com/sul-dlss/libsys-airflow/wiki/Vendor-Load:--Database-Model)

This model is required to capture file_part names from split up files of data that are of a size that will not cause issues with folio data import.

- [ ] Add file_part model under the vendor load plugin

**Comment by jmartin-sul** [comment]
@justinlittman is working on a spike that may obviate this, backlogging for now...

**Comment by aaron-collier** [comment]
I'm closing this in favor of #255 - If we decide we do need this, we can reopen/rewrite.
