### ISSUE TITLE
Vendor Load UI: Add vendor show page

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/libsys-airflow#355]
The initial iteration of this page should be very similar to the vendor list page, but will be listing the individual interfaces for the vendor.

Display in a simple table:

- Interface display name (will link to the vendor interface configuration/show page)
- data import profile name
- file regeex
- remote path
- processing delay
- processing dag

Note: Everything except the interface display name _can_ be blank - as they will have no values until they are configured. One approach to this UI could be to show the combination of vendor_interfaces from the database as well as any vendor_interfaces returned from FOLIO but not in the database (i.e. vendor_interfaces to be configured) or there could be a task to populate the database of vendors and interfaces and just reflect the DB.

**Comment by edsu** [comment]
It might be nice to have #367 in place first before going too far with this.
