### ISSUE TITLE
Add a command line utility to populate the vendor data

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/libsys-airflow#358]
Now that we have a vendor model and will be updating the list of vendors in the user interface to be based on the model instead of directly fetching the vendor list from FOLIO we need a way to seed the data.

We have a pattern in DLME to add useful command line utilities (https://github.com/sul-dlss/dlme-airflow/blob/main/bin/get) for this kind of work around data seeding or debugging. This makes something like `poetry run bin/seed_vendors` possible as an example.

Use the api query [here](https://github.com/sul-dlss/libsys-airflow/blob/main/libsys_airflow/plugins/vendor/vendors.py#L30) to populate the table. However, seed the database with all vendors to facility the paging/search functionality development.

If the vendor has any configured interfaces in FOLIO this utility should populate the vendor_interfaces table for this vendor.

**Comment by jmartin-sul** [comment]
WIP in https://github.com/sul-dlss/libsys-airflow/pull/363
