### ISSUE TITLE
vendor_loads db - can we set correct default/server_default for created and updated timestamp fields?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/libsys-airflow#373]
See PR #375 (replacement for #368) questions in the description for background.

At time of writing, this affects the `vendor_files` table, but it is also relevant to the `vendor_dataload` table when ticket #370 is implemented, and may be relevant to the `vendors` and `vendor_interfaces` table, depending 

For the `vendor_files` table in the vendor_loads database, we will have **created** and **updated** as DateTime fields.  It would be nice if we could:
- have the database automagically assign "now" to the "created" field rather than implementing this manually in the model or model manipulation code..   
    - I was reading in the alembic sqlalchemy docs and in google results about this ... and it seems a bit tricky to make sure that the default is the "now" of when the record is created, rather than the "now" of when the _table_ is created in the database.
    - Note that there is "server_default" which I believe is done at the postgres level, and there is "default" which is done at the app level when a record is created.  One of these may be easier than the other.  One of these may be more "correct" than the other.
- similarly to the "updated" field ... every time a record is saved, it _seems_ as if we should be able to get the database to assign "now" rather than implementing this manually in the model or model manipulation code.  (Same subpoints as above about what "now" means and doing it with the database vs the app code)

Note that in #375 / #368, Aaron says he is going to think about whether we should use UTC or local time.

**Comment by aaron-collier** [comment]
Closing in favor of #559 which describes the problem specific to our needs.
