### ISSUE TITLE
Add tests of vendor management view pages

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/libsys-airflow#377]
Next step as part of #332 is to set up tests of the vendor index page in the vendor_loads plugin. I have some (non-passing) starting code on this draft PR: https://github.com/sul-dlss/libsys-airflow/pull/376

**Comment by edsu** [comment]
I figured out that the reason for the 308 HTTP error is the URL needed a `/` on the end. But now the test is failing because of a database error:

```
FAILED tests/apps/vendor_app/test_vendor_management_view.py::test_vendor_views - airflow.exceptions.AirflowNotFoundException: The conn_id `vendor_loads` isn't defined
```

Maybe the `vendor_loads` isn't being set up for the tests to work?
