### ISSUE TITLE
Vendor list is paged and searchable by name and code

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/libsys-airflow#378]
Follow-on to #332 for making the vendor list ready for larger lists of vendors. Vendor list (/vendors) should be paged and searchable by name and code.

I thought https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/pagination/ might be useful, but it requires using [Flask-SQLAlchemy](https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/), which we are not currently using. We're using [SQLAlchemy ](https://www.sqlalchemy.org/) directly. It may be worth investigating implementing Flask-SQLAlchemy to make some of the UI tasks simpler.

**Comment by mjgiarlo** [comment]
I am finding this issue to be a rabbit hole without much prior knowledge of the libsys-airflow stack, so tossing back into Ready.

**Comment by mjgiarlo** [comment]
Whoever picks this up: @justinlittman suggests a more expedient way to handle this might be to use client-side datatables for paging and searching. I would concur.
