### ISSUE TITLE
Add a purge_files method to the VendorInterface model

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/libsys-airflow#381]
We only keep files in the vendor_interface data directory (i.e. `/dataloader/data/{vendor-id}/{interface-id}`) for 90 days.
Add a method to the `VendorInterface` model that when given a date removes an files older than the provided date from the data path shown above.

**Comment by justinlittman** [comment]
Is this for removing files or db records? (And if for files, I'd suggest that it the VendorInterface model is not the correct location for the code.)

**Comment by aaron-collier** [comment]
@justinlittman yeah - I think we're taking a slightly different approach (cc: @jermnelson) - and this may be closable.
