### ISSUE TITLE
Airflow Task: Use the VendorInterface.purge_files method to remove expired vendor data files

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/libsys-airflow#383]
Add a task to the `plugins/vendor` module that calculates `today's date - 90 days` and calls the purg_files methods for the given vendor and vendor_interface.

Add the task to the `data_fetcher` DAG.

**Comment by aaron-collier** [comment]
@jermnelson I think this may be closable now as we talked about moving files to the archive, not copying, correct?

**Comment by jermnelson** [comment]
@aaron-collier we're currently not moving but copying the files to the archive. I still think we'll need to remove the expired vendor data files because the copy-to-archive occurs before the file is processed/manipulated by a later DAG.

**Comment by aaron-collier** [comment]
Ah, thanks for clarifying.
