### ISSUE TITLE
Vendor Load UI: Add vendor_interface configuration edit page/modal

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/libsys-airflow#404]
Initiate the vendor_interface configuration page. This could be reached at `/vendors/{vendor_uuid}/{vendor_interface_uuid}/edit` or as a modal from the vendor_interface display page.

This should not be blocked now, and can be started while additions are ready when they become available.

![Screenshot 2023-05-18 at 10 21 07 AM](https://github.com/sul-dlss/libsys-airflow/assets/2294288/c00fee58-3cfb-4d73-9d19-90aeae2b1507)

- [x] Add a page to edit the interface configuration
- [x] Data entered into package name should go into the `processing_options` JSON field as `package_name`
- [x] Data entered into the marc fields should go into the `processing_options` JSON field as `delete_marc` and `change_marc` (see: https://github.com/sul-dlss/libsys-airflow/issues/430)
- [x] Use https://github.com/sul-dlss/libsys-airflow/blob/main/libsys_airflow/plugins/vendor/job_profiles.py to populate the list of import profiles.
- [x] Use the default processing dag until the utility to query for dags is complete.

**Comment by jmartin-sul** [comment]
"does the 910 have subfields, or does the value just go straight in?"
"should be a subfield A"

**Comment by edsu** [comment]
@aaron-collier did you happen to put some HTML together for that design image? I'm just being lazy :-)

**Comment by edsu** [comment]
I've taken a look at how Airflow does modals. It appears to be using the jQuery plugin in Bootstrap 3:

https://getbootstrap.com/docs/3.3/javascript/#modals

We could implement our edit form this way, but when Airtable upgrade to the latest Bootstrap, or replace Bootstrap altogether for something else (React, etc) we will need to update the edit functionality. If we implement it as a separate route, using plain old HTML then there will be less to update? 

Thoughts?

**Comment by lwrubel** [comment]
When I was initially looking at the form set-up (mistakenly thinking it was part of the upload ticket I took) it seemed to me that making it its own route might be the way to go, since the file upload and interface config is supposed to be linked from both the vendor page and an existing vendor_interface page. 

We still might want to use bootstrap forms though? Not sure how breakable they are from 3->4/5

**Comment by edsu** [comment]
@aaron-collier I'm assuming that `Processing Date` the `Processing Delay` in days?

**Comment by edsu** [comment]
Also, do we want to have `File Pattern` and `Remote Path` in here?

**Comment by edsu** [comment]
In addition to adding the `Processing Delay`, `File Pattern` and `Remote Pattern` above, and reordering a few things, I decided to modify the design slightly by adding two sections for `Removing Fields` and `Moving Fields` that work similarly by adding and removing "Rules". Here's what it looks like at the moment. I was thinking that the "MARC Processing Rules" section might need to hide for workflows that don't use the `default-data-processor` processing workflow?

I'm going to flip over to implementing the form validation and saving on the server side, but feedback on the form itself is welcome as I go.

**Comment by edsu** [comment]
This is what the editing looks like:

https://github.com/sul-dlss/libsys-airflow/assets/33829/f66d7f62-3cce-42d3-8dd1-7de53b3ec2eb
