### ISSUE TITLE
Support SFTP download

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/libsys-airflow#408]
Currently, only FTP download is supported; Amalivre and MarcIt require SFTP.

Note:
* Creating SFTP connections is supported: https://github.com/sul-dlss/libsys-airflow/pull/402
* Marcit is IP restricted, so testing is problematic.

**Comment by jmartin-sul** [comment]
discussed in planning, we think this is in progress by justin, but feel free to kick back to ready if that's wrong
