### ISSUE TITLE
Vendor Load UI: Manual upload interface

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/libsys-airflow#409]
An interface that allows a tech services staff member to manually upload a file, for a vendor, select the data import profile, processing dag, and processing schedule is required to allow for "upload only vendors" and situations where data has to manually be altered in order to pass data import.

This interface/modal should be available at:
- The vendor level, allowing selection of data import profile, processing dag, and dag schedule
- The vendor interface level, defaulting to the configured values for the data import profile, processing dag, and dag schedule but allowing selection to override.

- [ ] Add a link to the upload page (or open a modal) from the vendor page:

![Screenshot 2023-05-16 at 3 24 21 PM](https://github.com/sul-dlss/libsys-airflow/assets/2294288/46e91ffd-c117-43fe-9495-d37c1db013d6)

Notes:
- Processing date is optional. If not selected saving this page should immediately instantiate the selected processing dag with config.
- Processing date should be a date picker of some kind, if selected it should instantiate the selected processing dag with a start date of that selected.
- The marc configurations should be optional

**Comment by ndushay** [comment]
Is this done?  Or are there more bits?   

I've used the file upload a few times for testing ftp stuff

**Comment by justinlittman** [comment]
@aaron-collier Is the implementation good enough to close this ticket?

**Comment by aaron-collier** [comment]
Yes - this seems good, and the upload-only interface work/design will come shortly.
