### ISSUE TITLE
Switch Github Actions to use not macos

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/libsys-airflow#447]
Rather, it should us something similar to the docker image.

Specifically, this setting should be changed: https://github.com/sul-dlss/libsys-airflow/blob/main/.github/workflows/python-app.yml#L16

**Comment by ndushay** [comment]
Isn't this exactly what you suggested i NOT work on yesterday?   Getting the build to use docker images?

**Comment by justinlittman** [comment]
No, this is to use a version of linux that is similar to the docker image. Docker not involved.
