### ISSUE TITLE
Add delete_marc configuration to processing_options

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/libsys-airflow#461]
We currently hard code the marc fields that are removed during processing, this needs to be configurable as some vendors have additional fields to remove.

Add a `delete_marc` key to the `processing_options` JSON in order to surface this configuration to tasks.

This can be a comma separated text field or a list of individual fields, either approach is acceptable.

**Comment by lwrubel** [comment]
Is the `delete_marc` key intended to supplement the current `remove_fields` key, which [defaults to the hard-coded fields](https://github.com/sul-dlss/libsys-airflow/blob/f772ef19ccab7f81e09a9a846053047058ea2b9e/libsys_airflow/dags/vendor/default_data_processor.py#L72) but could be superseded by a different value? Or replace some aspect of that current config?
