### ISSUE TITLE
Marcit specific: Set 590 brief record note

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/libsys-airflow#463]
For MARCit, if a record does NOT have at least 1 035 with the value "OCoLC" then add a 590 subfield a with "MARCit brief record".

This is supported in the processing config for add files, see: https://github.com/sul-dlss/libsys-airflow/blob/main/libsys_airflow/plugins/vendor/marc.py#L85

As MARCit is the only vendor with this known use case, we have not exposed this option in the vendor management interface yet, so set this value in the processing config as shown in the above example before the `marc_processing` task of the default_processign_dag programmatically when the vendor is MARCit

**Comment by justinlittman** [comment]
@aaron-collier This is currently supported by MARC processing but not exposed in the UI.

**Comment by mjgiarlo** [comment]
I believe this should has been closed by #476. We should test to confirm, but I'm closing for now.

**Comment by aaron-collier** [comment]
@mjgiarlo ah, yes, apologies... this is supported (by the work in 476) but not exposed in the UI. Since marcit is the only vendor we know of with this need, I think it's OK (for now) if we wait to expose this in the UI and provide a workaround (like manually setting this in the config, or adding it to the config in code just for marcit).

I'll reopen and clarify in the ticket.
