### ISSUE TITLE
Completed Loads table's Status column showing "Filestatus.loaded"

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/libsys-airflow#466]
Status column on vendor interface view should have "loaded", "loading_error", etc rather than "FileStatus.loaded"

![Screenshot 2023-05-19 at 3 09 32 PM](https://github.com/sul-dlss/libsys-airflow/assets/1619369/d49646fc-c878-4566-a4e0-0716561d0634)

**Comment by ndushay** [comment]
fixed by #486?

**Comment by ndushay** [comment]
@justinlittman @aaron-collier did #486 fix this?

**Comment by aaron-collier** [comment]
I think so. Closing.
