### ISSUE TITLE
Vendor file download

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/libsys-airflow#495]
For the files listed on the vendor interface page, provide the ability to download (one at a time).

**Comment by edsu** [comment]
I am implementing `/interface/<int:interface_id>/file` (GET) for #480. It seems like that would be a good place for the download link to live? Or I guess it could go in the list of files as well.

**Comment by justinlittman** [comment]
Thanks for mentioning. Makes sense to put in both places.
