### ISSUE TITLE
Test function in items.py

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#50]
Test the following function in the `plugsin/folio/items.py` module:

- **post_folio_items_records** moderately difficult to test, requires using the tmp_path functionality in pytest to construct a JSON file of item records, should create a new kwarg parameter, with a default path of `/tmp/` similar to the `airflow` parameter is retrieved and set in: https://github.com/sul-dlss/folio-airflow/blob/e11ca3333877a2943490cee9583c563ba5fdf06e/plugins/folio/helpers.py#L19-L20
Similar to #49, confirm that we're generating the expected number of batches through the log messages should be sufficient to test this functionality.

**Comment by jgreben** [comment]
not doing anything special with items to test.
