### ISSUE TITLE
Vendor Management: User documentation

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/libsys-airflow#522]
Start the documentation on how users will use the application to manage automated and manual data loads. This may likely spawn additional tickets on specific pages/tasks, but for now, just capturing the need.

**Comment by ahafele** [comment]
Work in progress. This can stay assigned to me post work-cycle.

**Comment by ahafele** [comment]
Basic documentation here: https://docs.google.com/document/d/16nD8aq6eR4QOdrMfa87S3smHacu_rttdh1Id8KCtDOM/edit 
Will continue to adjust based on user feedback
