### ISSUE TITLE
Display import profile name on vendor page

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/libsys-airflow#537]
The column for import profile currently always displays None, but at least a few of these interfaces are configured.

![Screenshot 2023-05-31 at 1 59 50 PM](https://github.com/sul-dlss/libsys-airflow/assets/2294288/fa7cce9a-1feb-4005-9866-7d8eafebc01f)

**Comment by justinlittman** [comment]
This has already been fixed:
![image.png](https://images.zenhubusercontent.com/5d8270f64def500001d12f23/efc681e8-4f02-4aa4-ac58-90e6a34f4bf5)
