### ISSUE TITLE
Show if vendor has active interfaces on vendor page

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#565]
On [Vendor search page](https://sul-libsys-airflow-stage.stanford.edu/vendor_management/vendors) could we indicate of that vendor has active interfaces and allow to sort by this field? This will make it easier for user's of the app as we start to configure more interfaces for loading. 

May need input from @aaron-collier. I believe in design doc [here](https://docs.google.com/document/d/1xjbxiFWHT3THgaYC6mP1MS6VKoQKA2GWKey1TE0Y5cE/edit#bookmark=id.r3r6wtjnso1j)

The Vendor model includes a  `has_active_vendor_interfaces`

**Comment by justinlittman** [comment]
Done.
