### ISSUE TITLE
Show MARC Processing Rules on Interface page

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#567]
Could MARC Processing Rules be included on the Interface page with other config details? 

Eg. Include list of these 
![Screen Shot 2023-06-04 at 10.50.05 AM.png](https://images.zenhubusercontent.com/6259789bd12079728cab41a1/5b62086c-8667-411d-9299-257715e7408c)

On this screen
![Screen Shot 2023-06-04 at 10.50.14 AM.png](https://images.zenhubusercontent.com/6259789bd12079728cab41a1/bc4b4d6c-3019-4ad3-b211-29ac8f8a9350)

Minimum alternative could be 
**Marc processing = yes**

**Comment by mjgiarlo** [comment]
@aaron-collier Thx for the ✋🏻
