### ISSUE TITLE
File upload error: [Errno 21] Is a directory

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/libsys-airflow#576]
See https://app.honeybadger.io/projects/111133/faults/96577455

Also: https://sul-libsys-airflow-stage.stanford.edu/vendor_management/interfaces/2/file

**Comment by edsu** [comment]
Maybe it's a me problem but that HB URL is a Page Not Found:

<img width="1612" alt="Screenshot 2023-06-06 at 9 09 23 AM" src="https://github.com/sul-dlss/libsys-airflow/assets/33829/613a180e-e770-4f29-84ea-f9dc69be84b2">
