### ISSUE TITLE
Load report for EDI files

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#610]
Right now the Load Report email looks like MARC for edi loads. Should be adjusted to reflect EDI specifics. 

Example for https://folio-stage.stanford.edu/data-import/job-summary/a5c10bc4-38f0-406f-b2a5-66eb0322aec2  

FOLIO Catalog ~~MARC~~ **EDI** Load started on 2023-06-09 14:06:24.037627+00:00

Filename **inv574076.edi - https://folio-stage.stanford.edu/data-import/job-summary/a5c10bc4-38f0-406f-b2a5-66eb0322aec2**

~~0 bib record(s) read from MARC file.~~ **0 invoices read from EDI file.** For this we would need to count the number of occurrences of BGM+380. I've attached an example file. 

**1 SRS records created**

~~0 SRS records updated~~

~~0 SRS records discarded~~

~~0 SRS errors~~

~~0 Instance records created~~

~~0 Instance records updated~~

~~0 Instance records discarded~~

1  Invoice record created

**0 Instance errors**

Not critical but if possible, could we include the number of invoice lines created? See screenshot for where that info exists in report. 

![Screen Shot 2023-06-09 at 7.25.50 AM.png](https://images.zenhubusercontent.com/6259789bd12079728cab41a1/7e987df7-3992-47b9-bb3c-7770aac0d979)

**Comment by justinlittman** [comment]
@ahafele I did some work on getting the number of invoice lines created. Unfortunately, this requires the jobLogEntries API call. When that endpoint is called immediately after the job is completed, it doesn't return anything. At some point, it starts returning correct data. So while this allows getting the number of invoice lines, it requires gaming the Folio API, which adds complexity and the possibility of bugs. Unless it is critical, I would recommend against it.

**Comment by ahafele** [comment]
Thanks. Looking good so far. And thanks for investigating invoice lines. The user can just go to the FOLIO UI for this tally. 
For the count of invoices, ~~0 bib record(s) read from MARC file.~~ **0 invoices read from EDI file.** ,  in file we need to count the number of occurrences of BGM+380. Attached is an example file 
[inv574076.edi.txt](https://github.com/sul-dlss/libsys-airflow/files/11709622/inv574076.edi.txt)
