### ISSUE TITLE
Refactor fetch_only logic to include marc processing

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/libsys-airflow#613]
We have determined that the use of fetch_only interfaces, especially when testing data import profile work, need to have applied the marc processing.

Update the logic around fetch_only interfaces to either go through the processing dag up to the point of data import, or a marc_processing only dag. 

The result should still be an email to the users that a file was processed "but not loaded".

**Comment by justinlittman** [comment]
@aaron-collier The email work needs to be done. However, if I'm reading the code correctly the fetch_only workflow is already implemented as described. Do you have evidence to the contrary?
