### ISSUE TITLE
Refactor move marc fields to include indicators as matchers

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/libsys-airflow#615]
![Screenshot 2023-06-09 at 10 19 32 AM](https://github.com/sul-dlss/libsys-airflow/assets/2294288/a66fc58f-1874-4ef8-a390-03a59e81bffd)

When configuring an interface to move marc fields, use the indicator(s) (1 and 2) as matchers, all subfield content will be moved to the new destination field and indicator(s).

**Comment by justinlittman** [comment]
@aaron-collier @ahafele How do we handle blank indicators? So if a user does not provide an Indicator 1, does that mean match on anything or only match on a blank indicator?

**Comment by ahafele** [comment]
@justinlittman if blank in Original Field then match on anything. If blank in Destination Field then do not replace. 
For the Destination Field is there a character in pymarc to specifically indicate blank? e.g. `\` in Marcedit?

**Comment by justinlittman** [comment]
I think it treats a space character as a blank (no indicator).

**Comment by ahafele** [comment]
@justinlittman yes, that looks good. Thanks!
