### ISSUE TITLE
Reporting: Add a MARC 001 file report

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/libsys-airflow#636]
# Simplified

Add a section about 001 information to the current file load report.

# Original

When users are trouble shooting marc data, often times the key information they are looking at is in the 001 record, they would like an email report of all 001 records in the file:

On the Vendor Interface page:

- [ ] Add an "Actions" column to the Files Fetched with a "Send Reports" link
- [ ] Add a "Send Reports" link to the Actions column of the Sent to Data import table
- [ ] When clicked, read the marc file and collect all 001 records
- [ ] Email a report to the standard list serve:
    - [ ] Subject: [file name] MARC Report
    - [ ] Body: "The included 001 fields were identified in [filename]\nRecords: [list of 001 record content

@ahafele Please provide any changes to the above text that would make the email subject/body more helpful.

**Comment by justinlittman** [comment]
@aaron-collier  Since this may take some time, does this need another DAG (sigh)?

**Comment by aaron-collier** [comment]
@justinlittman good question, I think a DAG (big sigh) may be the best bet in order to take advantage of the existing email features. It is likely a very simple dag that this action could instantiate with a file record so it would be just a couple of tasks to build the report(s) and then email, but it only runs when trigged by the UI not on a schedule.
