### ISSUE TITLE
Change report email subject to include interface display name

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/libsys-airflow#655]
@ahafele [reports](https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/458#issuecomment-1590235702) that the report subject now includes the interface ID instead of the display name.

**Comment by justinlittman** [comment]
@ahafele I'm unclear which email report this is. Can you clarify and provide an example?

**Comment by ahafele** [comment]
Daily Fetch Report looks like this - 
(AMALIV-SUL) - 238dbe9d-c563-48dd-839b-61a64fe4a079 

Could it please follow the same pattern as the Daily Load Report?

Gobi - ebooks (YANKEE-SUL)

**Comment by ahafele** [comment]
Please remove the UUID. Thanks
