### ISSUE TITLE
exclude and report invoices with amount split fund distributions

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/libsys-airflow#713]
Exclude the entire invoice from the feeder file if there is an invoice line with an amount split, e.g. fund distribution has `"distributionType" : "amount"`. The report should be an email to ....

**Comment by scanedastanford** [comment]
The report should be emailed to sa-payments@lists.stanford.edu with the title "Rejected invoices for SUL" (similar to the one we are currently receiving). In the body, could it say "Amount split" with the vendor invoice number and a link to the invoice line?
