### ISSUE TITLE
Switch fallback Holdings Type in folio_migration_tools 

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#731]
Currently Monograph
Should be Unknown

**Comment by jermnelson** [comment]
@ahafele the *Unknown* Holdings Type has different UUIDs on test, stage and on production; what value should we use or would this wait after we refresh reference data on production and *Unknown* is added?

**Comment by jermnelson** [comment]
I believe Monograph comes from the FOLIO reference data so it has the same UUID across all of the environments.

**Comment by shelleydoljack** [comment]
Should it be added to the holdings-type.tsv and then the UUID will be consistent?

**Comment by jermnelson** [comment]
That is what I would recommend; that way going forward the default Holdings Type of Unknown could be set now.
