### ISSUE TITLE
503 error for Marcive

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#742]
I'm able to login to the [Marcive ](https://sul-libsys-airflow-stage.stanford.edu/vendor_management/interfaces/87)ftp server fine from bodoni but the VMA gets a 503 error. 

https://sul-libsys-airflow-stage.stanford.edu/log?execution_date=2023-08-17T18%3A46%3A51%2B00%3A00&task_id=ftp_download_task&dag_id=data_fetcher&map_index=-1

**Comment by vitustang** [comment]
Information about downloading files from Marcive via FTP or SFTP is here:
https://home.marcive.com/data-transfer-options/#CHG
It says: "NOTICE!  MARCIVE has locked down the FTP server.  Anonymous login requires an IP address to be provided for whitelisting." and "SFTP login information will be provided as needed. Contact customer service for credentials. [custserv@marcive.com](mailto:custserv@marcive.com)"

**Comment by ahafele** [comment]
Thanks @vitustang! Do we want to go ahead and switch to sftp?

**Comment by vitustang** [comment]
I don't know what we used before but using sftp would seem appropriate in the long run. I think Marcive said that they will phase out anonymous ftp.

**Comment by ahafele** [comment]
That makes sense to me Vitus. Should you request this or Linh?

**Comment by vitustang** [comment]
Alissa, I will request SFTP log in credentials from Marcive

**Comment by vitustang** [comment]
Here is the response from Marcive:
SFTP Login Info

Host: web.marcive.com
User name: Ma_56xCi_8ve
Password: 1x*BpT8FrsGx
use port 22 and make sure “FTP Server Secured” is checked

Wanda Leasman
GPO Processing Technician
Team Leader Customer Service
MARCIVE, Inc. 
[wleasman@marcive.com](mailto:wleasman@marcive.com)
[custserv@marcive.com](mailto:custserv@marcive.com)

**Comment by ahafele** [comment]
Thanks @vitustang! we can now connect with VMA. I will do some testing on stage and then edit the interfaces to reflect the new login info. I'll let you know when done.

**Comment by ahafele** [comment]
Done. Files fetched on stage for review.
