### ISSUE TITLE
distinguish stage emails from production

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#755]
Right now we are fetching files for both stage and production and the emails do not indicate in any way which app they are referring to. Is there a low bar way we could change this? e.g. subject line includes "stage"?

**Comment by jermnelson** [comment]
@ahafele - looking at the VMA code [here](https://github.com/sul-dlss/libsys-airflow/blob/97c921de1bf244532a603bb91c90a5400e525dd0/libsys_airflow/plugins/vendor/emails.py#L78) and [here](https://github.com/sul-dlss/libsys-airflow/blob/97c921de1bf244532a603bb91c90a5400e525dd0/libsys_airflow/plugins/vendor/emails.py#L203), the subject line in these emails should have the environment at the end in square brackets. Could you forward me an example?

**Comment by ahafele** [comment]
Oh you are right Jeremy! Sorry to have missed that. I was looking at the inbox view which cuts it off and not the single message view. This is good. We can create inbox filters based on this. Thanks!
