### ISSUE TITLE
Convert interfaces to Upload Only

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#763]
Hi Jeremy, here are the interfaces that need to be converted to Upload Only. 

Cambridge: https://sul-libsys-airflow-prod.stanford.edu/vendor_management/interfaces/62
Kanopy: https://sul-libsys-airflow-prod.stanford.edu/vendor_management/interfaces/48
Overdrive: https://sul-libsys-airflow-prod.stanford.edu/vendor_management/interfaces/61
Oxford: https://sul-libsys-airflow-prod.stanford.edu/vendor_management/interfaces/55
Michigan: https://sul-libsys-airflow-prod.stanford.edu/vendor_management/interfaces/57

**Comment by jermnelson** [comment]
@ahafele all of these interfaces have been converted to Upload Only.

**Comment by ahafele** [comment]
Thanks!
