### ISSUE TITLE
Correctly Handle Fractional Pennies for Invoice Lines

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#768]
When generating the [DA/TA/TX lines](https://github.com/sul-dlss/libsys-airflow/blob/f2a4037c96ad40d8ee15de9b17863d1844a257e0/libsys_airflow/plugins/orafin/models.py#L89) for the feeder-file based on the percentage Fund Distributions, we can get a mismatch between the sum of the lines and the sub-total for the Invoice Line because of rounding errors. The FOLIO Stripes front-end handles this issue by adjusting the last line the fund distribution and then works backwards adding one penny, see this [description](https://wiki.folio.org/display/DD/Prorated+Invoice+Adjustments#ProratedInvoiceAdjustments-FractionalPennies).

Here is a recent example:
![Screen Shot 2023-09-29 at 3 41 50 PM](https://github.com/sul-dlss/libsys-airflow/assets/71847/f60ebe66-0a4c-488c-93ce-17da346a04e0)

The sub-total for the invoice line is $857.85 with the fund distributions each at 50%. The UI assigns $428.92 and $428.93 respectively to each fund distribution that together equals the subtotal. For the feed-file we naively multiplied $857.85 by .5 and generated two DR lines of $428.93 (due to in part because of the rounding that occurs [here](https://github.com/sul-dlss/libsys-airflow/blob/f2a4037c96ad40d8ee15de9b17863d1844a257e0/libsys_airflow/plugins/orafin/models.py#L82)) that total $857.86 instead of $857.85. 

```
LIB10299     HD012580FEEDER         314854 10299                            20230920000000000857.85DR                              N30
LIB10299     DR000000000428.93TAX_EXEMPT          1065032-103-KAQJE-53270
LIB10299     DR000000000428.93TAX_EXEMPT          1065032-103-NAANK-53270
```

**Comment by scanedastanford** [comment]
@jermnelson thanks jeremy! here's a sample invoice in folio-test with one invoice line on 3 funds.: https://folio-test.stanford.edu/invoice/view/1af9a252-548d-4ae7-8a21-bb73f058c179 . This is another sample invoice that has the same funding split but with tax added this time: https://folio-test.stanford.edu/invoice/view/1af9a252-548d-4ae7-8a21-bb73f058c179
