### ISSUE TITLE
Boundwith DAG for Plugin

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#771]
We need a DAG to support ticket [770](https://github.com/sul-dlss/libsys-airflow/issues/770) that is triggered from a plugin. The DAG takes an uploaded CSV file containing rows of paired FOLIO Holdings HRIDs and Item barcodes, and then generates boundwith parent relationship from the Item barcode with the FOLIO Holdings HRID.

A markdown report should be generated at the end of the DAG that has a table with one row from the uploaded CSV along with the result of POST to Okapi along with any error messages per POST.

**Comment by shelleydoljack** [comment]
Folio won't create duplicate entries. I just tried on folio-test and got the following 422 response:
```
{
    "errors": [
        {
            "message": "lower(f_unaccent(jsonb ->> 'itemId'::text)), lower(f_unaccent(jsonb ->> 'holdingsRecordId'::text)) value already exists in table bound_with_part: 100ea71c-34fd-5a8a-909a-b7de39fcd3f4, 0b6e55e4-cad9-5dec-86ec-15c6559610d1",
            "type": "1",
            "code": "-1",
            "parameters": [
                {
                    "key": "lower(f_unaccent(jsonb ->> 'itemId'::text)), lower(f_unaccent(jsonb ->> 'holdingsRecordId'::text))",
                    "value": "100ea71c-34fd-5a8a-909a-b7de39fcd3f4, 0b6e55e4-cad9-5dec-86ec-15c6559610d1"
                }
            ]
        }
    ]
}
```

**Comment by shelleydoljack** [comment]
Lastly, @ahafele do we need to update the holdings record or item record or instance records with some admin note, both the trigger an update in SW and also document the creation of the boundwith relationship?

**Comment by ahafele** [comment]
Regarding checking for campus, that would be a nice feature but not one users will have when functionality comes to the UI. 

If the addition of the boundwith relationship triggers an item/holdings updated date change then SW should be ok. I will ask MD Subgroup for opinion on admin note addition.

**Comment by ahafele** [comment]
@shelleydoljack @jermnelson I finally gathered some feedback on the addition of an admin note - sorry for the delay. There was no very strong opinions about adding a note that documents the creation of the bw, but folks agreed it could be useful for troubleshooting. They would like to see it on the child holdings record or child holdings _and_ parent item. It should be formatted something like - SUL/LibrarySystems/BWcreatedby/_appuser_/20230807. 
So I guess my question is, how much trouble is it to add this? If alot, it might not outweigh the lukewarm feelings about needing it.
