### ISSUE TITLE
liableForVat false is not the case for folio-created vendor records

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/libsys-airflow#773]
Our migrated vendors will have liableForVat key in the data but it seems folio-created vendor records will not have that key if it is false. We got a key error for trying to transform an invoice when running the payments dag:
```
[2023-10-06, 15:42:46 UTC] {taskinstance.py:1824} ERROR - Task failed with exception
  + Exception Group Traceback (most recent call last):
  |   File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 220, in execute
  |     return_value = super().execute(context)
  |   File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
  |     return_value = self.execute_callable()
  |   File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
  |     return self.python_callable(*self.op_args, **self.op_kwargs)
  |   File "/opt/airflow/libsys_airflow/plugins/orafin/tasks.py", line 64, in transform_folio_data_task
  |     invoice, exclude = get_invoice(invoice_id, folio_client, converter)
  |   File "/opt/airflow/libsys_airflow/plugins/orafin/payments.py", line 93, in get_invoice
  |     invoice = converter.structure(invoice, Invoice)
  |   File "/home/airflow/.local/lib/python3.10/site-packages/cattrs/converters.py", line 334, in structure
  |     return self._structure_func.dispatch(cl)(obj, cl)
  |   File "<cattrs generated structure libsys_airflow.plugins.orafin.models.Invoice>", line 61, in structure_Invoice
  |     if errors: raise __c_cve('While structuring ' + 'Invoice', errors, __cl)
  | cattrs.errors.ClassValidationError: While structuring Invoice (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "<cattrs generated structure libsys_airflow.plugins.orafin.models.Invoice>", line 45, in structure_Invoice
    |     res['vendor'] = __c_structure_vendor(o['vendor'], __c_type_vendor)
    |   File "<cattrs generated structure libsys_airflow.plugins.orafin.models.Vendor>", line 24, in structure_Vendor
    |     if errors: raise __c_cve('While structuring ' + 'Vendor', errors, __cl)
    | cattrs.errors.ClassValidationError: While structuring Vendor (1 sub-exception)
    | Structuring class Invoice @ attribute vendor
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "<cattrs generated structure libsys_airflow.plugins.orafin.models.Vendor>", line 20, in structure_Vendor
      |     res['liableForVat'] = __c_structure_liableForVat(o['liableForVat'])
      | KeyError: 'liableForVat'
      | Structuring class Vendor @ attribute liableForVat
      +------------------------------------
```

**Comment by shelleydoljack** [comment]
update this line in the model: https://github.com/sul-dlss/libsys-airflow/blob/1d5adfe1a499e74250cd2987d2f527d84e711655/libsys_airflow/plugins/orafin/models.py#L18 to
`liableForVat: Union[None, bool]`
Also, check API docs to see what is required vs. optional for the other properties in our models.

**Comment by shelleydoljack** [comment]
@jermnelson I tried to add this to the models.py but when I update the fixture data in test_payments.py to reflect that the vendor doesn't have `viableForVat` key in the json data, the test still fails with the same error. See https://github.com/sul-dlss/libsys-airflow/commit/19655f6a919b42168e11f72496627119f03b7157

**Comment by jermnelson** [comment]
Hi Shelley, we need to specify a default value if the `liableForVat` is missing in the model definition (I should have looked at another example in the `models.py` ie line 55). So line 18 should be `liableForVat: Union[bool, None] = None`. This fixed all of the testing errors for me except for https://github.com/sul-dlss/libsys-airflow/blob/1d5adfe1a499e74250cd2987d2f527d84e711655/tests/orafin/test_payments.py#L153 which should be changed from `False` to `None` to pass.

**Comment by shelleydoljack** [comment]
Hmm, I'm not sure this is working as intended. When I add back `"liableForVat": False` to the vendor object in https://github.com/sul-dlss/libsys-airflow/blob/19655f6a919b42168e11f72496627119f03b7157/tests/orafin/test_payments.py#L89-L93 then the test fails because it is now set to default as `None` and the test is looking for None not False. To me, this means that all the migrated vendor records where `liableForVat: false` is in the json data will fail too.

**Comment by jermnelson** [comment]
@shelleydoljack, looking in the Models at [line 124](https://github.com/sul-dlss/libsys-airflow/blob/4b825b1f7bff09a2b5f72a03b37f524d7d3de0bb/libsys_airflow/plugins/orafin/models.py#L124) if the `liableForVat` is False, we would generate a `TA` line. Should we generate a `TA` if `liableForVat` is None? 

The other place that `liableForVat` is used is in the [tax_code](https://github.com/sul-dlss/libsys-airflow/blob/4b825b1f7bff09a2b5f72a03b37f524d7d3de0bb/libsys_airflow/plugins/orafin/models.py#L65-L70) function and if `liablbeForVat` being set to False or None returns the same value (USE_CA)

**Comment by shelleydoljack** [comment]
I think I figured out what to do: we want liableForVat default to False when it is missing from the organization json we get back. I created a [PR](https://github.com/sul-dlss/libsys-airflow/pull/777) with this logic. I think this fixes the issues you bring up in https://github.com/sul-dlss/libsys-airflow/issues/773#issuecomment-1756467401.
