### ISSUE TITLE
Pre-flight Emailed Invoice Report DAG

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#783]
When we were on Symphony, a test report was generated that checked the invoices for validity (using the same criteria we're using in the `payments_to_orafin` DAG) and then emailing the report at 4pm on Tuesdays and Thursdays ahead of the regular `payments_to_orafin` DAG runs on Wednesday and Fridays. This would allow for manual remediation by Acquisitions staff before the feeder-file is generated and sent to AP

**Comment by jgreben** [comment]
We no longer need to do this per Suzette
