### ISSUE TITLE
Request to clear files

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#792]
Please clear all Fetched and processed files (not Sent to Data Import and loaded) from these two interfaces 
https://sul-libsys-airflow-prod.stanford.edu/vendor_management/interfaces/20
https://sul-libsys-airflow-prod.stanford.edu/vendor_management/interfaces/19

**Comment by jermnelson** [comment]
@ahafele Done; files with status of "skipped" or "processed" have been deleted for these interfaces.

**Comment by ahafele** [comment]
thanks!
