### ISSUE TITLE
Investigate Metadb Integration

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#816]
As part of investigating MARC data-export out of FOLIO; we're considering how to use reports generated in [Metadb](https://librarydataplatform.org/) as a starting point for exporting MARC records out of FOLIO based on a set of criteria that are queried through Metadb. 

Possible choices:
- Use the [Postgres Operator](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/index.html) along with a  [Postgres Connection](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/connections/postgres.html#howto-connection-postgres)
- Custom sensor that picks up Metadb reports and process DAG
- Other?

**Comment by jgreben** [comment]
MetaDb is not the best choice because the updatedDate of the records are not included data points. We can query the folio Inventory and SRS Postgresql tables and use the airflow connectors.
