### ISSUE TITLE
Testing feedback

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#821]
- [x] Once submitted the webform returns a Run ID. This is hyper linked to the DAG info, but not all have access to this. Can we translate it to give the actual ID? Leave the link for those with access?
- [x] Errors should result in an email with error information. Right now when the DAG errors the user receives either no indication but also no email, or they receive the attached error screen with no information on what occurred. The user should be alerted to the error via email with some information about which file and/or IDs failed. 
- [x] Include submitted filename in email. 
- [ ] When you click the back button to get back to the BW webform it keeps the file selected file and now way to clear it out. There does not seem to be a submit another file button. _Note from Alissa: If you hit browse again you can overwrite the file. Might just be a staff training issue._

<img width="1173" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkUvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8811cee36cd79165fca5f66762216e3fcc1701a0/image.png" alt="image.png" />

**Comment by jermnelson** [comment]
Created ticket https://github.com/sul-dlss/libsys-airflow/issues/828 for the file upload issue.

**Comment by ahafele** [comment]
@jermnelson I see the new ticket you created for emailing errors but I thought we had addressed this in the above ticket? Or maybe it is only certain types of errors that get emailed now? Example of email with error below. 

Successful Relationships

0 boundwith relationships created

Failed Boundwidth Relationships

422 Client Error: Unprocessable Entity for url: https://okapi-test.stanford.edu/inventory-storage/bound-with-parts
Child Holding ID 0af10eb9-7110-594c-8f65-764331a3e5e8
Parent Item ID 45921b87-e5d5-5d66-a781-c71992241649

**Comment by jermnelson** [comment]
Hi @ahafele, yes I'm seeing some errors that are not being sent as email. I'll update ticket [844](https://github.com/sul-dlss/libsys-airflow/issues/844) to make this clear.
