### ISSUE TITLE
Change Email Link Text for AP Payment Reports

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#823]
Change the text link be the vendor invoice number (i.e. same as the Approved Invoices report, e.g. “[Vendor Invoice Number: 306529](https://folio.stanford.edu/invoice/view/857e06ce-04f1-48d6-81b1-4beeb77b904e)”)

**Comment by shelleydoljack** [comment]
Do they also want the AP error report emails to have the same link text? If so, it seems like here https://github.com/sul-dlss/libsys-airflow/blob/78fadae924d1365e5273b2f3c24ccc34d85715a3/libsys_airflow/plugins/orafin/reports.py#L35 we'd have to keep the vendor invoice number and pass it along, is that right?
