### ISSUE TITLE
Handle Error with Updating Invoice

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#836]
We're seeing a problem that happens about once a week in the `ap_payment_report.update-folio.update_invoices_task` task, where the Invoice PUT fails with a 400 error [here](https://github.com/sul-dlss/libsys-airflow/blob/8d08852d0606c0d191f4aea6b12adf276646ec7a/libsys_airflow/plugins/orafin/reports.py#L203). These errors most likely are  caused by an order line status being to set to `Fully Paid`. 

The workaround has been to manually fix the invoice by PUT to the adjusted invoice `invoice-storage` endpoint and then manually adjust the invoice lines as well. Here is a function I've been using to fix the problem that could be modified and used to fix this issue:

```python
def manually_paid_invoice(invoice_uuid):
    invoice = prod_client.folio_get(f"/invoice/invoices/{invoice_uuid}")
    if invoice["status"] != "Approved":
        print(f"Invoice status is not Approved {invoice['status']} {invoice_uuid}")
        return
    invoice["status"] = "Paid"
    put_result = httpx.put(f"{prod_client.okapi_url}/invoice-storage/invoices/{invoice_uuid}",
                           headers=prod_client.okapi_headers,
                           json=invoice)
    if put_result.status_code != 204:
        print(f"Error updating {invoice_uuid}, {put_result.status_code} {put_result.text}")
        return
    invoice_lines = prod_client.folio_get(f"/invoice-storage/invoice-lines?query=(invoiceId=={invoice_uuid})")
    for line in invoice_lines['invoiceLines']:
        line['invoiceLineStatus'] = "Paid"
        line_update_result = httpx.put(f"{prod_client.okapi_url}/invoice/invoice-lines/{line['id']}",
                                           headers=prod_client.okapi_headers,
                                           json=line,
                                           timeout=30.0)
        if line_update_result.status_code != 204:
            print(f"""Error updating line {line['id']} for invoice {invoice_uuid}
            {line_update_result.status_code}
            {line_update_result.text}""")
```

**Comment by shelleydoljack** [comment]
Suzette is going to do some testing to determine if we need to create a jira ticket in the mod-invoice project in folio jiras.

**Comment by jermnelson** [comment]
**Minor note**: for the retrieval of the invoice lines, make sure to include the `limit` parameter to the call as some invoices have more than 10 invoice lines.

**Comment by jermnelson** [comment]
Additionally, we need to make sure any of the purchase order lines (`poLineId`) in the Invoice Line have a updated `paymentStatus` to **Fully Paid**.

**Comment by jermnelson** [comment]
Pairing with @scanedastanford, we think we discovered the underlying problem that stems from an Order line having a Holding location with an "Invalid reference" that prevents the order line from being edited and saved (see https://folio.stanford.edu/inventory/view/40670b18-6458-5b15-8c3e-a509b293c116 for and example order line). This then causes upstream issues with the Invoice not being saved with the BL endpoint (but the ugly part is that the failure to save the Invoice doesn't rollback the invoice line statuses that could be set).

To fix the "Invalid reference" requires manual intervention so instead of trying to handling the error with using the non-BL endpoint to update the Invoice, Invoice-lines, PO etc., we will generate a new email with these invoices and the AP report information for manual remediation on the part of Acquisition staff.
