### ISSUE TITLE
Create file structure for data exports work files

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/libsys-airflow#853]
- [x] Modify `config/deploy.rb` to include new shared folders for `data-export-files`

N.b.

The file structure should end up looking something like this, and should be created when the files are created by the selection output and the marc processing output (using w+) (See tickets for selection run and marc processing modules).

- data-export-files
- - POD
- - - Instanceids
- - - Marc files
- - OCLC
- - - Instanceids
- - - Marc files
- - YBP
- - - Instanceids
- - - Marc files
- - WEST
- - - Instanceids
- - - Marc files
- - ShareVDE
- - - Instanceids
- - - Marc files
- - Google
- - - Instanceids
- - - Marc files

**Comment by jermnelson** [comment]
For the instance UUIDs as a csv file, use a date prefix with Hours (24 clock) like `YYYYMMDDH.csv` (this allows for multiple runs if needed). The MARC21 record will have the same base filename but with a `.mrc` suffix `YYYYMMDDH.mrc`.

**Comment by jgreben** [comment]
Fixed partially by #866

**Comment by jgreben** [comment]
Closed by work on several PRs.
