### ISSUE TITLE
Write a module to fetch and process MARC 

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/libsys-airflow#854]
- Function fetch raw marc from folio using selected uuids (using folio client)
- ~~Functions that apply the rules to the marc reocrd needed for all vendors~~ Moved to ticket #863 
- ~~Function to write processed marc to file location for vendor~~ Moved to ticket #864

See https://docs.google.com/document/d/1NAbY9L6G16DItIBjtRQKFDcL6NN5cWK8VfsFCT48vTA/edit for marc processing rules.

BLOCKS #863 
BLOCKS #864

**Comment by jermnelson** [comment]
Breaking out these bullet requirements into separate tickets.
