### ISSUE TITLE
DAG to remove old archives files

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/libsys-airflow#860]
Daily or weekly, remove archived files older than 30 days.

Is there already something in libsys-airflow that does this? What about the `purge_archived_files` DAG? Can this be repurposed? There is also the remove_archived_migration_files. Should it be removed?

**Comment by shelleydoljack** [comment]
Remove files older than 90 days.

Rename the VMA purge_archived_files to something more specific for VMA.
