### ISSUE TITLE
Generate a Data Export Report and send Email

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#861]
When an export has been sent to a vendor an email should go out to folio-load-reports@lists.stanford.edu with:
Subject/body:

"Vendor name: A data export has been sent to ..."
- Vendor name
- on Date
- Link to UI for downloading mrc or reports

_For example, orafin dags generate emails._

No report needed for FULL DUMP

**Comment by ahafele** [comment]
Need to think about emailing errors

**Comment by shelleydoljack** [comment]
We will know when a DAG run has some failed transmission of files. https://github.com/sul-dlss/libsys-airflow/blob/c664ace3093ee165542a603bb989931989e070bd/libsys_airflow/dags/data_exports/pod_transmission.py#L55

The failed files would be gathered in the next scheduled DAG run. For the full dump, the failed files would be retried once: https://github.com/sul-dlss/libsys-airflow/blob/c664ace3093ee165542a603bb989931989e070bd/libsys_airflow/dags/data_exports/full_dump_transmission.py#L61-L68

Regarding emails when we send records, I know we did this previously but I rather see emails when the DAG fails and not everytime it runs.

**Comment by ahafele** [comment]
The success email is for the stakeholders that might want to see what was sent. We will also want to send an email with a DAG fails and I have ticketed that separately [here](https://app.zenhub.com/workspaces/folio-at-stanford-628d6cab8c42a90248e5eb79/issues/gh/sul-dlss/folio-project-stanford/646) (note the AI generated acceptance criteria...:wow:)

**Comment by jgreben** [comment]
For now we will rely on the failed transmission dag email and also add a failed selection dag email.
