### ISSUE TITLE
Support for full Data Export of all MARC Records 

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#876]
Periodically we will need to do a full data export of all our MARC records (and for our initial Data Export) to various vendors. POD is one example that we did a full export on a monthly bases. The current work on the data selection, marc processing, and transmission DAGs and plugins maybe able to support this requirement but we will need to test.

**Comment by jgreben** [comment]
Detailed in:
https://github.com/sul-dlss/libsys-airflow/issues/897
https://github.com/sul-dlss/libsys-airflow/issues/898
