### ISSUE TITLE
Create full dump transmission dag

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/libsys-airflow#898]
- Supply vendor as config at runtime when triggering DAG:
e.g.
```
{
    "vendors": [
    	"",
      	"",
      	""
    ],
    "bucket": ""
}
```
- Provide a bucket default in dag (configured as airflow Variable)?
- Dag should use the existing tasks for transmitting the data in the bucket.
- Transmission tasks should be configured to be able to pull from bucket or filesystem as needed.
- - ~~Maybe need a new method or function to interrogate S3 instead of using pathlib?~~ Use s3Path
- Call exiting transmission tasks according to list of vendors in config.
- No archiving needed at this time
- POD will PULL from S3
- Vendors which need a PUSH:
- - ShareVDE?
- - others?

**Comment by jgreben** [comment]
Here is an s3 url for dev:
```
s3://folio-data-export-development/data-export-files/full-dump/marc-files/99000_100000.mrc
```

**Comment by shelleydoljack** [comment]
For supplying a configuration (params) when triggering the DAG, wouldn't we just need to know the vendor? Presumably the S3 bucket with the files wouldn't be different, it'd always be the path `data-export-files/full-dump/marc-files`. If the params is a list of vendors, then one DAG run would be responsible for sending the files to a list of vendors? I think maybe a DAG run should be sending files to one vendor. Or should a list of vendors equate to multiple DAG runs, one for each vendor? Is there a default vendor we should use when triggering the DAG or should it fail if there are no vendor params passed?

**Comment by jgreben** [comment]
> For supplying a configuration (params) when triggering the DAG, wouldn't we just need to know the vendor? Presumably the S3 bucket with the files wouldn't be different, it'd always be the path `data-export-files/full-dump/marc-files`. If the params is a list of vendors, then one DAG run would be responsible for sending the files to a list of vendors? I think maybe a DAG run should be sending files to one vendor. Or should a list of vendors equate to multiple DAG runs, one for each vendor? Is there a default vendor we should use when triggering the DAG or should it fail if there are no vendor params passed?

The bucket would just be (e.g.) `folio0data-export-development` or `folio-data-export-prod`, but yes the path would be the same for all of them.
