### ISSUE TITLE
OCLC Transmission DAG

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#900]
Taking the MARC files generated in PR #893 (update and new marc files for SUL, Hoover, Business, and Law), use the OCLC API to either [bib-create](https://developer.api.oclc.org/wc-metadata-v2#/Manage%20Bibliographic%20Records/bib-create) for new records or [bib-replace](https://developer.api.oclc.org/wc-metadata-v2#/Manage%20Bibliographic%20Records/bib-replace) for updated records.

We could look at using the [bib-match](https://developer.api.oclc.org/wc-metadata-v2#/Manage%20Bibliographic%20Records/match-bib) API endpoint to do a best match on new records to apply the OCLC Match on the MARC record and then do the [bib-replace](https://developer.api.oclc.org/wc-metadata-v2#/Manage%20Bibliographic%20Records/bib-replace) and update the MARC record in FOLIO.

**Comment by ahafele** [comment]
@jermnelson maybe we could talk this through. Right now, OCLC requirements don't include updates. Only "new" which should then be split into 3 categories - 

- Record has oclc number - set holdings
- Record has more than one OCLC number - Report out to staff
- Record has no OCLC record id - send full record to OCLC (a check with bib-match makes sense here but if none is found, we could want to create)
