### ISSUE TITLE
Postgres Volume not shared during deployments

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#94]
The docker Postgres volumes is being recreated for every deployment on `sul-libsys-airflow-dev.stanford.edu`.

Logging into server and running `docker volume ls | grep "postgres"` results in

```bash
docker volume ls | grep "postgres"
local     20220323202745_postgres-db-volume
local     20220419215623_postgres-db-volume
local     20220419220250_postgres-db-volume
local     20220419222627_postgres-db-volume
local     20220531172358_postgres-db-volume
local     20220531174928_postgres-db-volume
local     20220531211228_postgres-db-volume
local     20220602182838_postgres-db-volume
local     20220602184122_postgres-db-volume
local     20220602185918_postgres-db-volume
local     20220602190236_postgres-db-volume
local     20220602210140_postgres-db-volume
```

**Comment by justinlittman** [comment]
Should deployed airflow be using Ops-managed PG and Redis instead of Docker PG and Redis?

**Comment by jermnelson** [comment]
> Should deployed airflow be using Ops-managed PG and Redis instead of Docker PG and Redis?

@justinlittman The current PG and Redis set-up was suggested by Ops when we initially set-up Airflow using docker-compose. Maybe this has changed in the meantime with DLME Airflow moving to on-prem. Do you want to follow-up with Ops on this issue?

**Comment by justinlittman** [comment]
closing in favor of #272
