### ISSUE TITLE
VMA - files not found for interface

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#944]
Interface has been successfully retrieving files until beginning of April. Interface configuration has not changed, DAG says [0 files found](https://sul-libsys-airflow-prod.stanford.edu/dags/data_fetcher/grid?run_id=manual__2024-04-29T15%3A38%3A57%2B00%3A00&execution_date=2024-04-29+15%3A38%3A57%2B00%3A00&tab=logs&dag_run_id=manual__2024-04-29T15%3A38%3A57%2B00%3A00&task_id=ftp_download_task). Regex is correct. 

Interface - https://sul-libsys-airflow-prod.stanford.edu/vendor_management/interfaces/43 
Should be retrieving the following - 
-rw-r--r--    1 incabook   incabook        16334 Apr 10 09:41 ST26673.mrc
-rw-r--r--    1 incabook   incabook        16016 Apr 10 09:41 ST26674.mrc
-rw-r--r--    1 incabook   incabook        17279 Apr 10 09:41 ST26677.mrc
-rw-r--r--    1 incabook   incabook        16446 Apr 10 09:41 ST26678.mrc
-rw-r--r--    1 incabook   incabook        18469 Apr 24 15:36 ST26708.mrc
-rw-r--r--    1 incabook   incabook        18349 Apr 24 15:36 ST26709.mrc
-rw-r--r--    1 incabook   incabook        17779 Apr 24 15:36 ST26710.mrc

**Comment by jermnelson** [comment]
Looking at the Interface, I think the regular expression should be adjusted to `^Stanford/ST\d+.*\.mrc$`, the "Stanford" directory is being prepended to the list of files so the regular expression is failing.

**Comment by ahafele** [comment]
Is this a change on our end and therefore across all interfaces? If so, most of our regexes will now be wrong and I wonder if we can revert back to how it behaved previously?

**Comment by jermnelson** [comment]
I don't think it is across all of the interfaces but it may help to check those interfaces that have a *Remote Path* value to see they are working as expected with the regex.

**Comment by ahafele** [comment]
I tried updating the interface with the suggested regex and got a [download error](https://sul-libsys-airflow-prod.stanford.edu/log?execution_date=2024-04-29T19%3A15%3A58%2B00%3A00&task_id=ftp_download_task&dag_id=data_fetcher&map_index=-1).

**Comment by jermnelson** [comment]
@shelleydoljack found the following Stackoverflow [answer](https://superuser.com/questions/1499536/how-to-change-the-ftp-directory-format-in-response-to-a-nlist-atnlst-instruct) that seems related to this ticket.
