### ISSUE TITLE
Transform MARC for deleted records for POD

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/libsys-airflow#953]
According to https://github.com/pod4lib/aggregator/wiki/Data-requirements#record-delete-data MARC records using d in position 05in the MARC Leader are considered deleted. Deletes sent as MARC21 binary records may be included in a file with added and updated records. Do an additional marc transformation for UUIDS selected as deletes.

**Comment by shelleydoljack** [comment]
I think we decided to create a text file of folio hrid's instead. See https://github.com/sul-dlss/libsys-airflow/issues/955.
