### ISSUE TITLE
delete files from S3 prior to select_all_records dag

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/libsys-airflow#959]
Since the batch size and concurrent jobs configuration has an effect on the filenames of files written to S3, we would need to delete the files in S3 so that the transmission DAG doesn't send duplicate records that are spread across different files. Maybe we delete files in S3 at the beginning of the selection DAG to avoid this potential issue.

**Comment by jgreben** [comment]
In the meantime we can run this:
```
aws s3 rm s3://folio-data-export-development/full-dump-marc-files --profile folio-dev --recursive
```
