### ISSUE TITLE
CSV upload test failed

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#964]
Update : No longer failing. 
Says submitted but I don't see which DAG it kicks off or any outcome. Should it kick off the selection dag?

**Comment by jgreben** [comment]
Probably still needs to be updated for "updates/deletes".

**Comment by jgreben** [comment]
Fixed by https://github.com/sul-dlss/libsys-airflow/pull/963

**Comment by jgreben** [comment]
@ahafele The next scheduled dag run will normally include the uploaded file of IDs, otherwise you would need to trigger a manual run for the vendor that you selected.

**Comment by ahafele** [comment]
@jgreben got it. Which DAG do the ids get added to? E.g. for POD would it be the selection DAG?

**Comment by jgreben** [comment]
Yes, the selection dags will pick up the uploaded IDs when triggered.
