### ISSUE TITLE
Schedule run for select_pod dag is failing

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#967]
https://sul-libsys-airflow-dev.stanford.edu/dags/select_pod_records/grid?run_id=scheduled__2024-05-07T00%3A00%3A00%2B00%3A00&execution_date=2024-05-07+00%3A00%3A00%2B00%3A00&tab=graph&dag_run_id=scheduled__2024-05-07T00%3A00%3A00%2B00%3A00&task_id=fetch_record_ids_from_folio

**Comment by jgreben** [comment]
Works for manual runs not scheduled runs.

**Comment by jgreben** [comment]
Fixed by https://github.com/sul-dlss/libsys-airflow/pull/973

**Comment by jgreben** [comment]
This should be fixed. Please reopen if it still append or happens again.

**Comment by jgreben** [comment]
Reopening. There are still empty file handles in updates and deletes lists.

**Comment by jgreben** [comment]
Now fixed by https://github.com/sul-dlss/libsys-airflow/pull/983

**Comment by jgreben** [comment]
Closing. Re-open if needed.
