### ISSUE TITLE
File naming for ShareVDE uploads

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/libsys-airflow#970]
TBD.

Old info here: https://docs.google.com/document/d/1VPiemFQQ2uiErQEhdJ01WqllRRWQolImfHGQu4pOGv8/edit

**Comment by ahafele** [comment]
Asked on Slack. No response yet.

**Comment by ahafele** [comment]
Ongoing conversation on slack. Will comment here when we know specifics

**Comment by ahafele** [comment]
@dlrueda  sent sample of compressed marcxml (POD) for sharevde to review. Closing this and will create new tickets when we are ready to send them data.
